import type { CommandCategory, LatexCommand } from "../types/command";

const makeCommand = (
  id: string,
  command: string,
  insertTemplate: string,
  previewLatex: string,
  labelVi: string,
  labelEn: string,
  category: CommandCategory,
  defaultPriority = 72,
  aliases: string[] = [],
  keywords: string[] = [],
): LatexCommand => ({
  id,
  command,
  insertTemplate,
  previewLatex,
  labelVi,
  labelEn,
  aliases,
  keywords,
  category,
  defaultPriority,
  supportedInMathMode: true,
});

const complexCommands: LatexCommand[] = [
  // 对现有选区添加上标、下标或上下限
  makeCommand("scripts", "_{}^{}", "\\placeholder{}_{\\placeholder{}}^{\\placeholder{}}", "X_{a}^{b}", "Thêm giới hạn trên/dưới", "Add upper/lower limits", "structure", 96, ["limits", "scripts"], ["Add upper/lower limits", "Thêm giới hạn trên/dưới"]),
  makeCommand("lower-script", "_{}", "\\placeholder{}_{\\placeholder{}}", "X_{a}", "Thêm giới hạn dưới", "Add lower limit", "structure", 92, ["lower limit", "subscript"], ["Add lower limit", "Thêm giới hạn dưới"]),
  makeCommand("upper-script", "^{}", "\\placeholder{}^{\\placeholder{}}", "X^{b}", "Thêm giới hạn trên", "Add upper limit", "structure", 92, ["upper limit", "superscript"], ["Add upper limit", "Thêm giới hạn trên"]),

  // 基础结构
  makeCommand("smallfrac", "\\tfrac", "\\tfrac{\\placeholder{}}{\\placeholder{}}", "\\tfrac{a}{b}", "Phân đoạn văn bản", "Text fraction", "structure", 79, ["tfrac"], ["Text fraction", "Phân đoạn văn bản"]),
  makeCommand("displayfrac", "\\dfrac", "\\dfrac{\\placeholder{}}{\\placeholder{}}", "\\dfrac{a}{b}", "Hiển thị phân số", "Display fraction", "structure", 78, ["dfrac"], ["Display fraction", "Hiển thị phân số"]),
  makeCommand("brackets", "\\left[", "\\left[\\placeholder{}\\right]", "\\left[x\\right]", "Chân đế", "Brackets", "structure", 81, ["square brackets"], ["Brackets", "Chân đế"]),
  makeCommand("braces", "\\left\\{", "\\left\\{\\placeholder{}\\right\\}", "\\left\\{x\\right\\}", "Niềng răng", "Braces", "structure", 80, ["curly braces"], ["Braces", "Niềng răng"]),
  makeCommand("anglebrackets", "\\langle", "\\left\\langle\\placeholder{}\\right\\rangle", "\\langle x\\rangle", "Giá đỡ góc", "Angle brackets", "structure", 77, ["angle brackets"], ["Angle brackets", "Giá đỡ góc"]),
  makeCommand("floor", "\\lfloor", "\\left\\lfloor\\placeholder{}\\right\\rfloor", "\\lfloor x\\rfloor", "Tầng", "Floor", "structure", 76, ["floor"], ["Floor", "Tầng"]),
  makeCommand("ceil", "\\lceil", "\\left\\lceil\\placeholder{}\\right\\rceil", "\\lceil x\\rceil", "Trần nhà", "Ceiling", "structure", 76, ["ceil", "ceiling"], ["Ceiling", "Trần nhà"]),
  makeCommand("overline", "\\overline", "\\overline{\\placeholder{}}", "\\overline{x}", "Nội dung", "Overline", "structure", 75, ["bar", "overline"], ["Overline", "Nội dung"]),
  makeCommand("hat", "\\hat", "\\hat{\\placeholder{}}", "\\hat{x}", "Giọng mũ", "Hat accent", "structure", 84, ["hat"], ["Hat accent", "Giọng mũ"]),
  makeCommand("widehat", "\\widehat", "\\widehat{\\placeholder{}}", "\\widehat{ABC}", "Mũ rộng", "Wide hat", "structure", 78, ["wide hat"], ["Wide hat", "Mũ rộng"]),
  makeCommand("tilde", "\\tilde", "\\tilde{\\placeholder{}}", "\\tilde{x}", "Dấu ngã", "Tilde accent", "structure", 83, ["tilde"], ["Tilde accent", "Dấu ngã"]),
  makeCommand("widetilde", "\\widetilde", "\\widetilde{\\placeholder{}}", "\\widetilde{ABC}", "Dấu ngã rộng", "Wide tilde", "structure", 77, ["wide tilde"], ["Wide tilde", "Dấu ngã rộng"]),
  makeCommand("dotaccent", "\\dot", "\\dot{\\placeholder{}}", "\\dot{x}", "Dấu chấm", "Dot accent", "structure", 80, ["dot"], ["Dot accent", "Dấu chấm"]),
  makeCommand("ddotaccent", "\\ddot", "\\ddot{\\placeholder{}}", "\\ddot{x}", "Dấu hai chấm", "Double-dot accent", "structure", 79, ["double dot", "ddot"], ["Double-dot accent", "Dấu hai chấm"]),
  makeCommand("checkaccent", "\\check", "\\check{\\placeholder{}}", "\\check{x}", "Kiểm tra giọng", "Check accent", "structure", 73, ["check accent"], ["Check accent", "Kiểm tra giọng"]),
  makeCommand("breveaccent", "\\breve", "\\breve{\\placeholder{}}", "\\breve{x}", "Giọng Breve", "Breve accent", "structure", 72, ["breve"], ["Breve accent", "Giọng Breve"]),
  makeCommand("acuteaccent", "\\acute", "\\acute{\\placeholder{}}", "\\acute{x}", "Giọng cấp tính", "Acute accent", "structure", 71, ["acute"], ["Acute accent", "Giọng cấp tính"]),
  makeCommand("graveaccent", "\\grave", "\\grave{\\placeholder{}}", "\\grave{x}", "Giọng nghiêm túc", "Grave accent", "structure", 70, ["grave"], ["Grave accent", "Giọng nghiêm túc"]),
  makeCommand("ringaccent", "\\mathring", "\\mathring{\\placeholder{}}", "\\mathring{x}", "Giọng chuông", "Ring accent", "structure", 69, ["ring accent"], ["Ring accent", "Giọng chuông"]),
  makeCommand("overrightarrow", "\\overrightarrow", "\\overrightarrow{\\placeholder{}}", "\\overrightarrow{AB}", "Mũi tên qua phải", "Over-arrow right", "structure", 77, ["over arrow"], ["Over-arrow right", "Mũi tên qua phải"]),
  makeCommand("overleftarrow", "\\overleftarrow", "\\overleftarrow{\\placeholder{}}", "\\overleftarrow{AB}", "Mũi tên qua trái", "Over-arrow left", "structure", 74, ["over left arrow"], ["Over-arrow left", "Mũi tên qua trái"]),
  makeCommand("underline", "\\underline", "\\underline{\\placeholder{}}", "\\underline{x}", "Gạch chân", "Underline", "structure", 73, ["underline"], ["Underline", "Gạch chân"]),
  makeCommand("overbrace", "\\overbrace", "\\overbrace{\\placeholder{}}^{\\placeholder{}}", "\\overbrace{a+\\cdots+a}^{n}", "Nẹp quá mức", "Overbrace", "structure", 72, ["overbrace"], ["Overbrace", "Nẹp quá mức"]),
  makeCommand("underbrace", "\\underbrace", "\\underbrace{\\placeholder{}}_{\\placeholder{}}", "\\underbrace{a+\\cdots+a}_{n}", "Nẹp lót", "Underbrace", "structure", 72, ["underbrace"], ["Underbrace", "Nẹp lót"]),
  makeCommand("cases", "\\begin{cases}", "\\begin{cases}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{cases}", "f(x)=\\begin{cases}x&x>0\\\\0&x\\leq0\\end{cases}", "Vỏ", "Cases", "structure", 85, ["cases", "piecewise"], ["Cases", "Vỏ"]),
  makeCommand("boxed", "\\boxed", "\\boxed{\\placeholder{}}", "\\boxed{x}", "Đóng hộp", "Boxed", "structure", 70, ["boxed", "box"], ["Boxed", "Đóng hộp"]),

  // 微积分与常用函数
  makeCommand("intplain", "\\int", "\\int \\placeholder{}\\,\\mathrm{d}\\placeholder{}", "\\int f(x)\\,\\mathrm{d}x", "Tích phân bất định", "Indefinite integral", "calculus", 99, ["indefinite integral", "integral"], ["Indefinite integral", "Tích phân bất định"]),
  makeCommand("iint-bounds", "\\iint", "\\iint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}A", "\\iint_D^S f\\,\\mathrm{d}A", "Tích phân kép giới hạn", "Bounded double integral", "calculus", 91, ["bounded double integral"], ["Bounded double integral", "Tích phân kép giới hạn"]),
  makeCommand("iiint-bounds", "\\iiint", "\\iiint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V^W f\\,\\mathrm{d}V", "Tích phân bội ba giới hạn", "Bounded triple integral", "calculus", 90, ["bounded triple integral"], ["Bounded triple integral", "Tích phân bội ba giới hạn"]),
  makeCommand("oint-bounds", "\\oint", "\\oint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}\\placeholder{}", "\\oint_C^D f\\,\\mathrm{d}s", "Tích phân đường viền giới hạn", "Bounded contour integral", "calculus", 89, ["bounded contour integral"], ["Bounded contour integral", "Tích phân đường viền giới hạn"]),
  makeCommand("sum-finite", "\\sum", "\\sum_{\\placeholder{}=\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\sum_{k=1}^{n}a_k", "Tổng hữu hạn", "Finite sum", "calculus", 98, ["finite sum"], ["Finite sum", "Tổng hữu hạn"]),
  makeCommand("prod-finite", "\\prod", "\\prod_{\\placeholder{}=\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\prod_{k=1}^{n}a_k", "Sản phẩm hữu hạn", "Finite product", "calculus", 92, ["finite product"], ["Finite product", "Sản phẩm hữu hạn"]),
  makeCommand("lineintegral", "\\int", "\\int_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}s", "\\int_C f\\,\\mathrm{d}s", "Tích phân đường thẳng", "Line integral", "calculus", 96, ["line integral", "path integral"], ["Line integral", "Tích phân đường thẳng"]),
  makeCommand("surfaceintegral", "\\iint", "\\iint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}S", "\\iint_S f\\,\\mathrm{d}S", "Tích phân bề mặt", "Surface integral", "calculus", 95, ["surface integral", "double integral"], ["Surface integral", "Tích phân bề mặt"]),
  makeCommand("iiint", "\\iiint", "\\iiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V f\\,\\mathrm{d}V", "Tích phân ba", "Triple integral", "calculus", 94, ["triple integral"], ["Triple integral", "Tích phân ba"]),
  makeCommand("volumeintegral", "\\iiint", "\\iiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V f\\,\\mathrm{d}V", "Tích phân khối lượng", "Volume integral", "calculus", 93, ["volume integral"], ["Volume integral", "Tích phân khối lượng"]),
  makeCommand("closed-surface-integral", "\\oiint", "\\oiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}S", "\\oiint_S \\mathbf{F}\\cdot\\mathrm{d}\\mathbf{S}", "Tích phân mặt kín", "Closed surface integral", "calculus", 92, ["closed surface integral", "oiint"], ["Closed surface integral", "Tích phân mặt kín"]),
  makeCommand("closed-volume-integral", "\\oiiint", "\\oiiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\oiiint_V f\\,\\mathrm{d}V", "Tích phân khối đóng", "Closed volume integral", "calculus", 87, ["closed volume integral", "oiiint"], ["Closed volume integral", "Tích phân khối đóng"]),
  makeCommand("derivative", "\\frac{d}{dx}", "\\frac{\\mathrm{d}\\placeholder{}}{\\mathrm{d}\\placeholder{}}", "\\frac{\\mathrm{d}f}{\\mathrm{d}x}", "Đạo hàm", "Derivative", "calculus", 91, ["derivative"], ["Derivative", "Đạo hàm"]),
  makeCommand("secondderivative", "\\frac{d^2}{dx^2}", "\\frac{\\mathrm{d}^{2}\\placeholder{}}{\\mathrm{d}\\placeholder{}^{2}}", "\\frac{\\mathrm{d}^{2}f}{\\mathrm{d}x^{2}}", "Đạo hàm bậc hai", "Second derivative", "calculus", 83, ["second derivative"], ["Second derivative", "Đạo hàm bậc hai"]),
  makeCommand("partialsecond", "\\partial^2", "\\frac{\\partial^{2}\\placeholder{}}{\\partial\\placeholder{}^{2}}", "\\frac{\\partial^{2}f}{\\partial x^{2}}", "Phần thứ hai", "Second partial", "calculus", 82, ["second partial"], ["Second partial", "Phần thứ hai"]),
  makeCommand("mixedpartial", "\\partial^2", "\\frac{\\partial^{2}\\placeholder{}}{\\partial\\placeholder{}\\partial\\placeholder{}}", "\\frac{\\partial^{2}f}{\\partial x\\partial y}", "Hỗn hợp một phần", "Mixed partial", "calculus", 81, ["mixed partial"], ["Mixed partial", "Hỗn hợp một phần"]),
  makeCommand("evalbar", "\\left.", "\\left.\\placeholder{}\\right|_{\\placeholder{}}^{\\placeholder{}}", "\\left.F(x)\\right|_a^b", "Đánh giá", "Evaluation", "calculus", 80, ["evaluate"], ["Evaluation", "Đánh giá"]),
  makeCommand("series", "\\sum", "\\sum_{\\placeholder{}=0}^{\\infty} \\placeholder{}", "\\sum_{n=0}^{\\infty}a_n", "Chuỗi vô hạn", "Infinite series", "calculus", 97, ["series", "summation"], ["Infinite series", "Chuỗi vô hạn"]),
  makeCommand("productseries", "\\prod", "\\prod_{\\placeholder{}=1}^{\\infty} \\placeholder{}", "\\prod_{n=1}^{\\infty}a_n", "Sản phẩm vô tận", "Infinite product", "calculus", 94, ["infinite product", "product"], ["Infinite product", "Sản phẩm vô tận"]),
  makeCommand("coproduct", "\\coprod", "\\coprod_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\coprod_{i=1}^{n} A_i", "Bản sao", "Coproduct", "calculus", 84, ["coproduct"], ["Coproduct", "Bản sao"]),
  makeCommand("lim-infty", "\\lim", "\\lim_{\\placeholder{}\\to\\infty} \\placeholder{}", "\\lim_{x\\to\\infty}f(x)", "Giới hạn ở vô cực", "Limit at infinity", "calculus", 95, ["limit infinity"], ["Limit at infinity", "Giới hạn ở vô cực"]),
  makeCommand("lim-left", "\\lim", "\\lim_{\\placeholder{}\\to\\placeholder{}^{-}} \\placeholder{}", "\\lim_{x\\to a^-}f(x)", "Giới hạn bên trái", "Left-hand limit", "calculus", 93, ["left limit"], ["Left-hand limit", "Giới hạn bên trái"]),
  makeCommand("lim-right", "\\lim", "\\lim_{\\placeholder{}\\to\\placeholder{}^{+}} \\placeholder{}", "\\lim_{x\\to a^+}f(x)", "Giới hạn bên phải", "Right-hand limit", "calculus", 93, ["right limit"], ["Right-hand limit", "Giới hạn bên phải"]),
  makeCommand("log", "\\log", "\\log_{\\placeholder{}}\\left(\\placeholder{}\\right)", "\\log_a x", "Lôgarit", "Logarithm", "calculus", 86, ["logarithm"], ["Logarithm", "Lôgarit"]),
  makeCommand("ln", "\\ln", "\\ln\\left(\\placeholder{}\\right)", "\\ln x", "Gỗ tự nhiên", "Natural log", "calculus", 87, ["natural log"], ["Natural log", "Gỗ tự nhiên"]),
  makeCommand("exp", "\\exp", "\\exp\\left(\\placeholder{}\\right)", "\\exp(x)", "Hàm mũ", "Exponential", "calculus", 85, ["exponential"], ["Exponential", "Hàm mũ"]),
  makeCommand("sin", "\\sin", "\\sin\\left(\\placeholder{}\\right)", "\\sin x", "Sin", "Sine", "calculus", 89, ["sine"], ["Sine", "Sin"]),
  makeCommand("cos", "\\cos", "\\cos\\left(\\placeholder{}\\right)", "\\cos x", "cosin", "Cosine", "calculus", 89, ["cosine"], ["Cosine", "cosin"]),
  makeCommand("tan", "\\tan", "\\tan\\left(\\placeholder{}\\right)", "\\tan x", "Tiếp tuyến", "Tangent", "calculus", 84, ["tangent"], ["Tangent", "Tiếp tuyến"]),
  makeCommand("arcsin", "\\arcsin", "\\arcsin\\left(\\placeholder{}\\right)", "\\arcsin x", "Arcsin", "Arcsine", "calculus", 74, ["arcsine"], ["Arcsine", "Arcsin"]),
  makeCommand("min", "\\min", "\\min_{\\placeholder{}}\\placeholder{}", "\\min_x f(x)", "Tối thiểu", "Minimum", "calculus", 78, ["minimum"], ["Minimum", "Tối thiểu"]),
  makeCommand("max", "\\max", "\\max_{\\placeholder{}}\\placeholder{}", "\\max_x f(x)", "Tối đa", "Maximum", "calculus", 78, ["maximum"], ["Maximum", "Tối đa"]),

  // 矩阵与线性代数
  makeCommand("matrixplain2", "\\begin{matrix}", "\\begin{matrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{matrix}", "\\begin{matrix}a&b\\\\c&d\\end{matrix}", "Ma trận trơn", "Plain matrix", "matrix", 82, ["matrix"], ["Plain matrix", "Ma trận trơn"]),
  makeCommand("Bmatrix2", "\\begin{Bmatrix}", "\\begin{Bmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{Bmatrix}", "\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}", "Ma trận nẹp", "Brace matrix", "matrix", 80, ["Bmatrix"], ["Brace matrix", "Ma trận nẹp"]),
  makeCommand("Vmatrix2", "\\begin{Vmatrix}", "\\begin{Vmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{Vmatrix}", "\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}", "Ma trận thanh đôi", "Double-bar matrix", "matrix", 78, ["Vmatrix"], ["Double-bar matrix", "Ma trận thanh đôi"]),
  makeCommand("rowvector", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} & \\placeholder{} & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a&b&c\\end{bmatrix}", "Vectơ hàng", "Row vector", "matrix", 86, ["row vector"], ["Row vector", "Vectơ hàng"]),
  makeCommand("colvector", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} \\\\ \\placeholder{} \\\\ \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a\\\\b\\\\c\\end{bmatrix}", "Vectơ cột", "Column vector", "matrix", 86, ["column vector"], ["Column vector", "Vectơ cột"]),
  makeCommand("det", "\\det", "\\det\\left(\\placeholder{}\\right)", "\\det(A)", "Toán tử xác định", "Determinant operator", "matrix", 82, ["det"], ["Determinant operator", "Toán tử xác định"]),
  makeCommand("trace", "\\operatorname{tr}", "\\operatorname{tr}\\left(\\placeholder{}\\right)", "\\operatorname{tr}(A)", "Dấu vết", "Trace", "matrix", 78, ["trace", "tr"], ["Trace", "Dấu vết"]),
  makeCommand("rank", "\\operatorname{rank}", "\\operatorname{rank}\\left(\\placeholder{}\\right)", "\\operatorname{rank}(A)", "Thứ hạng", "Rank", "matrix", 78, ["rank"], ["Rank", "Thứ hạng"]),
  makeCommand("norm", "\\lVert", "\\left\\lVert\\placeholder{}\\right\\rVert", "\\lVert\\mathbf{x}\\rVert", "Định mức", "Norm", "matrix", 81, ["norm"], ["Norm", "Định mức"]),
  makeCommand("unitvector", "\\hat", "\\hat{\\mathbf{\\placeholder{}}}", "\\hat{\\mathbf{e}}", "Vectơ đơn vị", "Unit vector", "matrix", 84, ["unit vector"], ["Unit vector", "Vectơ đơn vị"]),

  // 物理常用结构
  makeCommand("expectation", "\\langle", "\\left\\langle\\placeholder{}\\right\\rangle", "\\langle A\\rangle", "Giá trị kỳ vọng", "Expectation value", "physics", 90, ["expectation"], ["Expectation value", "Giá trị kỳ vọng"]),
  makeCommand("braket", "\\langle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\phi|\\psi\\rangle", "Giá đỡ", "Bra-ket", "physics", 92, ["braket", "inner product"], ["Bra-ket", "Giá đỡ"]),
  makeCommand("commutator", "[", "\\left[\\placeholder{},\\placeholder{}\\right]", "[A,B]", "Cổ góp", "Commutator", "physics", 88, ["commutator"], ["Commutator", "Cổ góp"]),
  makeCommand("anticommutator", "\\{", "\\left\\{\\placeholder{},\\placeholder{}\\right\\}", "\\{A,B\\}", "Bộ phản chuyển mạch", "Anticommutator", "physics", 82, ["anticommutator"], ["Anticommutator", "Bộ phản chuyển mạch"]),
  makeCommand("timederivative", "\\dot", "\\dot{\\placeholder{}}", "\\dot{x}", "Đạo hàm thời gian", "Time derivative", "physics", 86, ["dot derivative"], ["Time derivative", "Đạo hàm thời gian"]),
  makeCommand("timesecond", "\\ddot", "\\ddot{\\placeholder{}}", "\\ddot{x}", "Đạo hàm lần thứ hai", "Second time derivative", "physics", 84, ["double dot"], ["Second time derivative", "Đạo hàm lần thứ hai"]),
  makeCommand("outerproduct", "|\\psi\\rangle\\langle\\phi|", "|\\placeholder{}\\rangle\\langle\\placeholder{}|", "|\\psi\\rangle\\langle\\phi|", "Sản phẩm bên ngoài", "Outer product", "physics", 91, ["outer product", "ket bra"], ["Outer product", "Sản phẩm bên ngoài"]),
  makeCommand("matrixelement", "\\langle\\phi|\\hat A|\\psi\\rangle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\phi|\\hat A|\\psi\\rangle", "Phần tử ma trận", "Matrix element", "physics", 90, ["matrix element"], ["Matrix element", "Phần tử ma trận"]),
  makeCommand("expectation-operator", "\\langle\\psi|\\hat A|\\psi\\rangle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\psi|\\hat A|\\psi\\rangle", "Kỳ vọng của nhà điều hành", "Operator expectation", "physics", 89, ["operator expectation"], ["Operator expectation", "Kỳ vọng của nhà điều hành"]),
  makeCommand("time-ordering", "\\mathcal{T}", "\\mathcal{T}\\left\\{\\placeholder{}\\right\\}", "\\mathcal{T}\\{A(t)B(t')\\}", "Thứ tự thời gian", "Time ordering", "physics", 75, ["time ordering"], ["Time ordering", "Thứ tự thời gian"]),
];

type SimpleDefinition = [
  id: string,
  command: string,
  labelVi: string,
  labelEn: string,
  category: CommandCategory,
  priority?: number,
  aliases?: string[],
  keywords?: string[],
];

const simpleDefinitions: SimpleDefinition[] = [
  // 矩阵
  ["transpose", "^{\\mathsf{T}}", "Chuyển cung", "Transpose", "matrix", 84, ["transpose"], ["Transpose", "Chuyển cung"]],
  ["inverse", "^{-1}", "Nghịch đảo", "Inverse", "matrix", 85, ["inverse"], ["Inverse", "Nghịch đảo"]],
  ["dotproduct", "\\cdot", "Sản phẩm chấm", "Dot product", "matrix", 83, ["dot product"], ["Dot product", "Sản phẩm chấm"]],
  ["crossproduct", "\\times", "Sản phẩm chéo", "Cross product", "matrix", 83, ["cross product"], ["Cross product", "Sản phẩm chéo"]],

  // 希腊字母
  ["epsilon", "\\epsilon", "Epsilon", "Epsilon", "greek", 82],
  ["varepsilon", "\\varepsilon", "Biến thể epsilon", "Variant epsilon", "greek", 80],
  ["zeta", "\\zeta", "Zeta", "Zeta", "greek", 78],
  ["eta", "\\eta", "Eta", "Eta", "greek", 78],
  ["vartheta", "\\vartheta", "Biến thể theta", "Variant theta", "greek", 78],
  ["iota", "\\iota", "Iota", "Iota", "greek", 76],
  ["kappa", "\\kappa", "Kappa", "Kappa", "greek", 80],
  ["nu", "\\nu", "Nữ", "Nu", "greek", 79],
  ["xi", "\\xi", "Xi", "Xi", "greek", 76],
  ["rho", "\\rho", "Rho", "Rho", "greek", 82],
  ["varrho", "\\varrho", "Biến thể rho", "Variant rho", "greek", 72],
  ["tau", "\\tau", "Tàu", "Tau", "greek", 81],
  ["upsilon", "\\upsilon", "Upsilon", "Upsilon", "greek", 70],
  ["phi", "\\phi", "Phi", "Phi", "greek", 86],
  ["varphi", "\\varphi", "Biến thể phi", "Variant phi", "greek", 84],
  ["chi", "\\chi", "Chí", "Chi", "greek", 74],
  ["psi", "\\psi", "Psi", "Psi", "greek", 84],
  ["Gamma", "\\Gamma", "Gamma", "Gamma", "greek", 76],
  ["Delta", "\\Delta", "Đồng bằng", "Delta", "greek", 84],
  ["Theta", "\\Theta", "Theta", "Theta", "greek", 72],
  ["Lambda", "\\Lambda", "Lambda", "Lambda", "greek", 76],
  ["Xi", "\\Xi", "Xi", "Xi", "greek", 68],
  ["Pi", "\\Pi", "Pi", "Pi", "greek", 74],
  ["Sigma", "\\Sigma", "Sigma", "Sigma", "greek", 78],
  ["Phi", "\\Phi", "Phi", "Phi", "greek", 76],
  ["Psi", "\\Psi", "Psi", "Psi", "greek", 78],
  ["Omega", "\\Omega", "Omega", "Omega", "greek", 82],
  ["varpi", "\\varpi", "Biến thể pi", "Variant pi", "greek", 73],
  ["varsigma", "\\varsigma", "Sigma cuối cùng", "Final sigma", "greek", 71],
  ["digamma", "\\digamma", "Hình ảnh mờ", "Digamma", "greek", 68],

  // 关系符号
  ["lt", "<", "Nhỏ hơn", "Less than", "relation", 92],
  ["gt", ">", "Lớn hơn", "Greater than", "relation", 92],
  ["equiv", "\\equiv", "Tương đương", "Equivalent", "relation", 88],
  ["sim", "\\sim", "Tương tự", "Similar", "relation", 82],
  ["simeq", "\\simeq", "tiệm cận bằng nhau", "Asymptotically equal", "relation", 80],
  ["cong", "\\cong", "Đồng đẳng", "Congruent", "relation", 78],
  ["ll", "\\ll", "Ít hơn nhiều", "Much less", "relation", 82],
  ["gg", "\\gg", "Tuyệt vời hơn nhiều", "Much greater", "relation", 82],
  ["parallel", "\\parallel", "Song song", "Parallel", "relation", 79],
  ["perp", "\\perp", "Vuông góc", "Perpendicular", "relation", 81],
  ["mid", "\\mid", "Chia", "Divides", "relation", 74],
  ["nmid", "\\nmid", "Không chia", "Does not divide", "relation", 72],
  ["prec", "\\prec", "Trước", "Precedes", "relation", 68],
  ["succ", "\\succ", "Thành công", "Succeeds", "relation", 68],
  ["leqq", "\\leqq", "Nhỏ hơn hoặc bằng (gấp đôi)", "Less than or equal (double)", "relation", 77],
  ["geqq", "\\geqq", "Lớn hơn hoặc bằng (gấp đôi)", "Greater than or equal (double)", "relation", 77],
  ["lneq", "\\lneq", "Nhỏ hơn nhưng không bằng", "Less than but not equal", "relation", 75],
  ["gneq", "\\gneq", "Lớn hơn nhưng không bằng", "Greater than but not equal", "relation", 75],
  ["lesssim", "\\lesssim", "Nhỏ hơn hoặc tương tự", "Less than or similar", "relation", 74],
  ["gtrsim", "\\gtrsim", "Lớn hơn hoặc tương đương", "Greater than or similar", "relation", 74],
  ["lessapprox", "\\lessapprox", "Nhỏ hơn hoặc xấp xỉ bằng", "Less than or approximately equal", "relation", 73],
  ["gtrapprox", "\\gtrapprox", "Lớn hơn hoặc xấp xỉ bằng", "Greater than or approximately equal", "relation", 73],
  ["preceq", "\\preceq", "Đi trước hoặc bằng", "Precedes or equals", "relation", 72],
  ["succeq", "\\succeq", "Thành công hoặc bằng", "Succeeds or equals", "relation", 72],
  ["asymp", "\\asymp", "Tương đương tiệm cận", "Asymptotically equivalent", "relation", 76],
  ["doteq", "\\doteq", "Dấu chấm bằng", "Dotted equals", "relation", 71],
  ["triangleq", "\\triangleq", "Được định nghĩa là", "Defined as", "relation", 78],
  ["models", "\\models", "Model", "Models", "relation", 74],
  ["vdash", "\\vdash", "Chứng minh", "Proves", "relation", 73],
  ["dashv", "\\dashv", "Cửa quay ngược", "Reverse turnstile", "relation", 67],
  ["bowtie", "\\bowtie", "Quan hệ thắt nơ", "Bowtie relation", "relation", 66],
  ["smile", "\\smile", "Nụ cười quan hệ", "Smile relation", "relation", 64],
  ["frown", "\\frown", "Quan hệ cau mày", "Frown relation", "relation", 64],

  // 集合与逻辑
  ["subseteq", "\\subseteq", "Tập con hoặc bằng", "Subset or equal", "set", 88],
  ["supset", "\\supset", "Siêu bộ", "Superset", "set", 86],
  ["supseteq", "\\supseteq", "Superset hoặc bằng", "Superset or equal", "set", 84],
  ["emptyset", "\\emptyset", "Bộ trống", "Empty set", "set", 90],
  ["setminus", "\\setminus", "Đặt chênh lệch", "Set difference", "set", 82],
  ["land", "\\land", "Hợp lý và", "Logical and", "set", 86],
  ["lor", "\\lor", "Hợp lý hoặc", "Logical or", "set", 86],
  ["neg", "\\neg", "Không logic", "Logical not", "set", 84],
  ["Nset", "\\mathbb{N}", "Số tự nhiên", "Natural numbers", "set", 88],
  ["Zset", "\\mathbb{Z}", "Số nguyên", "Integers", "set", 88],
  ["Qset", "\\mathbb{Q}", "Lý lẽ", "Rationals", "set", 86],
  ["Rset", "\\mathbb{R}", "Số thực", "Real numbers", "set", 92],
  ["Cset", "\\mathbb{C}", "Số phức", "Complex numbers", "set", 90],

  // 箭头
  ["uparrow", "\\uparrow", "Mũi tên lên", "Up arrow", "arrow", 84],
  ["downarrow", "\\downarrow", "Mũi tên xuống", "Down arrow", "arrow", 84],
  ["updownarrow", "\\updownarrow", "Mũi tên lên xuống", "Up-down arrow", "arrow", 76],
  ["Leftarrow", "\\Leftarrow", "Mũi tên kép trái", "Left double arrow", "arrow", 82],
  ["Leftrightarrow", "\\Leftrightarrow", "Nếu và chỉ nếu", "If and only if", "arrow", 88],
  ["mapsto", "\\mapsto", "Bản đồ tới", "Maps to", "arrow", 86],
  ["longrightarrow", "\\longrightarrow", "Mũi tên dài phải", "Long right arrow", "arrow", 78],
  ["longleftarrow", "\\longleftarrow", "Mũi tên trái dài", "Long left arrow", "arrow", 76],
  ["hookrightarrow", "\\hookrightarrow", "Mũi tên móc phải", "Right hook arrow", "arrow", 72],
  ["rightharpoonup", "\\rightharpoonup", "Cây lao phải", "Right harpoon", "arrow", 70],
  ["leftharpoonup", "\\leftharpoonup", "Cây lao trái", "Left harpoon", "arrow", 70],
  ["rightleftarrows", "\\rightleftarrows", "Mũi tên cân bằng", "Equilibrium arrows", "arrow", 78],
  ["longleftrightarrow", "\\longleftrightarrow", "Mũi tên dài trái phải", "Long left-right arrow", "arrow", 78],
  ["Longrightarrow", "\\Longrightarrow", "Mũi tên kép dài bên phải", "Long right double arrow", "arrow", 82],
  ["Longleftarrow", "\\Longleftarrow", "Mũi tên kép dài bên trái", "Long left double arrow", "arrow", 80],
  ["Longleftrightarrow", "\\Longleftrightarrow", "Mũi tên tương đương dài", "Long equivalence arrow", "arrow", 84],
  ["longmapsto", "\\longmapsto", "Mũi tên bản đồ dài tới", "Long maps-to arrow", "arrow", 76],
  ["hookleftarrow", "\\hookleftarrow", "Mũi tên móc trái", "Left hook arrow", "arrow", 72],
  ["rightharpoondown", "\\rightharpoondown", "Lao lao xuống bên phải", "Right harpoon down", "arrow", 69],
  ["leftharpoondown", "\\leftharpoondown", "Cây lao bên trái hạ xuống", "Left harpoon down", "arrow", 69],
  ["rightleftharpoons", "\\rightleftharpoons", "Lao móc phải trái", "Right-left harpoons", "arrow", 79],
  ["leftrightharpoons", "\\leftrightharpoons", "Lao móc trái phải", "Left-right harpoons", "arrow", 77],
  ["nearrow", "\\nearrow", "Mũi tên hướng Đông Bắc", "North-east arrow", "arrow", 68],
  ["nwarrow", "\\nwarrow", "Mũi tên hướng Tây Bắc", "North-west arrow", "arrow", 68],
  ["searrow", "\\searrow", "Mũi tên hướng Đông Nam", "South-east arrow", "arrow", 68],
  ["swarrow", "\\swarrow", "Mũi tên hướng Tây Nam", "South-west arrow", "arrow", 68],
  ["circlearrowright", "\\circlearrowright", "Mũi tên tròn theo chiều kim đồng hồ", "Clockwise circular arrow", "arrow", 66],
  ["circlearrowleft", "\\circlearrowleft", "Mũi tên tròn ngược chiều kim đồng hồ", "Counterclockwise circular arrow", "arrow", 66],
  ["rightsquigarrow", "\\rightsquigarrow", "Mũi tên phải nguệch ngoạc", "Squiggly right arrow", "arrow", 70],
  ["twoheadrightarrow", "\\twoheadrightarrow", "Mũi tên phải hai đầu", "Two-headed right arrow", "arrow", 70],
  ["twoheadleftarrow", "\\twoheadleftarrow", "Mũi tên trái hai đầu", "Two-headed left arrow", "arrow", 70],

  // 物理常用
  ["planck", "h", "Hằng số Planck", "Planck constant", "physics", 88],
  ["kb", "k_{\\mathrm{B}}", "Hằng số Boltzmann", "Boltzmann constant", "physics", 91],
  ["epsilon0", "\\varepsilon_{0}", "Độ thấm chân không", "Vacuum permittivity", "physics", 89],
  ["mu0", "\\mu_{0}", "Độ thấm chân không", "Vacuum permeability", "physics", 89],
  ["lightspeed", "c", "Tốc độ ánh sáng", "Speed of light", "physics", 86],
  ["electroncharge", "e", "Điện tích cơ bản", "Elementary charge", "physics", 84],
  ["laplacian", "\\nabla^{2}", "Laplacian", "Laplacian", "physics", 88],
  ["divergence", "\\nabla\\cdot", "Phân kỳ", "Divergence", "physics", 86],
  ["curl", "\\nabla\\times", "Uốn", "Curl", "physics", 86],
  ["dagger", "\\dagger", "Dao găm", "Dagger", "physics", 84],
  ["ddagger", "\\ddagger", "Dao găm đôi", "Double dagger", "physics", 72],
  ["tensorproduct", "\\otimes", "Sản phẩm Tenor", "Tensor product", "physics", 88],
  ["directsum", "\\oplus", "Tổng trực tiếp", "Direct sum", "physics", 82],
  ["hamiltonian-operator", "\\hat{H}", "Toán tử Hamilton", "Hamiltonian operator", "physics", 92],
  ["momentum-operator", "\\hat{\\mathbf{p}}", "Toán tử động lượng", "Momentum operator", "physics", 90],
  ["angular-momentum-operator", "\\hat{\\mathbf{L}}", "Toán tử xung lượng góc", "Angular momentum operator", "physics", 88],
  ["spin-operator", "\\hat{\\mathbf{S}}", "Toán tử quay", "Spin operator", "physics", 87],
  ["electric-field", "\\mathbf{E}", "Điện trường", "Electric field", "physics", 88],
  ["magnetic-field", "\\mathbf{B}", "Từ trường", "Magnetic field", "physics", 88],
  ["electric-displacement", "\\mathbf{D}", "Dịch chuyển điện", "Electric displacement", "physics", 80],
  ["magnetic-intensity", "\\mathbf{H}", "Cường độ từ trường", "Magnetic field intensity", "physics", 80],
  ["current-density", "\\mathbf{J}", "Mật độ dòng điện", "Current density", "physics", 82],
  ["kronecker-delta", "\\delta_{ij}", "đồng bằng Kronecker", "Kronecker delta", "physics", 84],
  ["levi-civita", "\\varepsilon_{ijk}", "Biểu tượng Levi-Civita", "Levi-Civita symbol", "physics", 82],
  ["four-gradient", "\\partial_{\\mu}", "Độ dốc bốn", "Four-gradient", "physics", 81],
  ["metric-tensor", "g_{\\mu\\nu}", "Tenxơ hệ mét", "Metric tensor", "physics", 81],
  ["dalembertian", "\\Box", "Toán tử D'Alembert", "D'Alembert operator", "physics", 80],
  ["imaginary-unit", "\\mathrm{i}", "Đơn vị tưởng tượng", "Imaginary unit", "physics", 76],
  ["euler-number", "\\mathrm{e}", "Số Euler", "Euler's number", "physics", 76],
  ["reduced-compton", "\\ell", "Kịch bản ell", "Script ell", "physics", 68],
  ["pauli-vector", "\\boldsymbol{\\sigma}", "Vector Pauli", "Pauli vector", "physics", 83],
];

const simpleCommands = simpleDefinitions.map(
  ([id, command, labelVi, labelEn, category, priority = 72, aliases = [], keywords = []]) =>
    makeCommand(
      id,
      command,
      command,
      command,
      labelVi,
      labelEn,
      category,
      priority,
      aliases,
      keywords,
    ),
);

export const additionalCommands: LatexCommand[] = [
  ...complexCommands,
  ...simpleCommands,
];
