import type { LatexCommand } from "../types/command";
import { additionalCommands } from "./additionalCommands.ts";
import { latestSharedCommands } from "./latestSharedCommands.ts";

const baseCommandRegistry: LatexCommand[] = [
  { id: "frac", command: "\\frac", insertTemplate: "\\frac{\\placeholder{}}{\\placeholder{}}", previewLatex: "\\frac{a}{b}", labelVi: "Phân số", labelEn: "Fraction", aliases: ["divide", "fraction"], keywords: ["Fraction", "Phân số", "divide", "fraction"], category: "structure", defaultPriority: 100, supportedInMathMode: true },
  { id: "sqrt", command: "\\sqrt", insertTemplate: "\\sqrt{\\placeholder{}}", previewLatex: "\\sqrt{x}", labelVi: "Căn bậc hai", labelEn: "Square root", aliases: ["root", "square root"], keywords: ["Square root", "Căn bậc hai", "root", "square root"], category: "structure", defaultPriority: 98, supportedInMathMode: true },
  { id: "nthroot", command: "\\sqrt", insertTemplate: "\\sqrt[\\placeholder{}]{\\placeholder{}}", previewLatex: "\\sqrt[n]{x}", labelVi: "Gốc thứ N", labelEn: "Nth root", aliases: ["nth root"], keywords: ["Nth root", "Gốc thứ N", "nth root"], category: "structure", defaultPriority: 82, supportedInMathMode: true },
  { id: "power", command: "^", insertTemplate: "^{\\placeholder{}}", previewLatex: "x^{n}", labelVi: "Chỉ số trên", labelEn: "Superscript", aliases: ["power", "superscript"], keywords: ["Superscript", "Chỉ số trên", "power", "superscript"], category: "structure", defaultPriority: 90, supportedInMathMode: true },
  { id: "subscript", command: "_", insertTemplate: "_{\\placeholder{}}", previewLatex: "x_{i}", labelVi: "Chỉ số đăng ký", labelEn: "Subscript", aliases: ["index", "subscript"], keywords: ["Subscript", "Chỉ số đăng ký", "index", "subscript"], category: "structure", defaultPriority: 88, supportedInMathMode: true },
  { id: "parentheses", command: "\\left", insertTemplate: "\\left(\\placeholder{}\\right)", previewLatex: "\\left(x\\right)", labelVi: "Dấu ngoặc đơn", labelEn: "Parentheses", aliases: ["bracket", "parentheses"], keywords: ["Parentheses", "Dấu ngoặc đơn", "bracket", "parentheses"], category: "structure", defaultPriority: 84, supportedInMathMode: true },
  { id: "absolute", command: "\\left|", insertTemplate: "\\left|\\placeholder{}\\right|", previewLatex: "\\left|x\\right|", labelVi: "Giá trị tuyệt đối", labelEn: "Absolute value", aliases: ["abs", "absolute"], keywords: ["Absolute value", "Giá trị tuyệt đối", "abs", "absolute"], category: "structure", defaultPriority: 83, supportedInMathMode: true },
  { id: "binom", command: "\\binom", insertTemplate: "\\binom{\\placeholder{}}{\\placeholder{}}", previewLatex: "\\binom{n}{k}", labelVi: "Nhị thức", labelEn: "Binomial", aliases: ["choose", "binomial"], keywords: ["Binomial", "Nhị thức", "choose", "binomial"], category: "structure", defaultPriority: 72, supportedInMathMode: true },
  { id: "overset", command: "\\overset", insertTemplate: "\\overset{\\placeholder{}}{\\placeholder{}}", previewLatex: "\\overset{a}{b}", labelVi: "Quá mức", labelEn: "Overset", aliases: ["over set", "upper annotation"], keywords: ["Overset", "Quá mức", "over set", "upper annotation"], category: "structure", defaultPriority: 70, supportedInMathMode: true },
  { id: "underset", command: "\\underset", insertTemplate: "\\underset{\\placeholder{}}{\\placeholder{}}", previewLatex: "\\underset{a}{b}", labelVi: "Underset", labelEn: "Underset", aliases: ["under set", "lower annotation"], keywords: ["Underset", "Underset", "under set", "lower annotation"], category: "structure", defaultPriority: 69, supportedInMathMode: true },
  { id: "overunderset", command: "\\overunderset", insertTemplate: "\\overset{\\placeholder{}}{\\underset{\\placeholder{}}{\\placeholder{}}}", previewLatex: "\\overunderset{a}{c}{b}", labelVi: "Đặt dưới mức quá mức", labelEn: "Over-underset", aliases: ["over under set", "upper lower annotation"], keywords: ["Over-underset", "Đặt dưới mức quá mức", "over under set", "upper lower annotation"], category: "structure", defaultPriority: 68, supportedInMathMode: true },
  { id: "stackrel", command: "\\stackrel", insertTemplate: "\\stackrel{\\placeholder{}}{\\placeholder{}}", previewLatex: "\\stackrel{a}{b}", labelVi: "Quan hệ xếp chồng", labelEn: "Stacked relation", aliases: ["stack relation"], keywords: ["Stacked relation", "Quan hệ xếp chồng", "stack relation"], category: "structure", defaultPriority: 67, supportedInMathMode: true },
  { id: "stackbin", command: "\\stackbin", insertTemplate: "\\stackbin{\\placeholder{}}{\\placeholder{}}", previewLatex: "\\stackbin{a}{b}", labelVi: "Xếp chồng nhị phân", labelEn: "Stacked binary", aliases: ["stack binary"], keywords: ["Stacked binary", "Xếp chồng nhị phân", "stack binary"], category: "structure", defaultPriority: 66, supportedInMathMode: true },
  { id: "overarc", command: "\\overarc", insertTemplate: "\\overarc{\\placeholder{}}", previewLatex: "\\overarc{AB}", labelVi: "Trên cung", labelEn: "Over arc", aliases: ["over arc"], keywords: ["Over arc", "Trên cung", "over arc"], category: "structure", defaultPriority: 65, supportedInMathMode: true },
  { id: "overline", command: "\\overline", insertTemplate: "\\overline{\\placeholder{}}", previewLatex: "\\overline{AB}", labelVi: "Nội dung", labelEn: "Overline", aliases: ["over line"], keywords: ["Overline", "Nội dung", "over line"], category: "structure", defaultPriority: 65, supportedInMathMode: true },
  { id: "overbrace", command: "\\overbrace", insertTemplate: "\\overbrace{\\placeholder{}}", previewLatex: "\\overbrace{a+b}", labelVi: "Nẹp quá mức", labelEn: "Overbrace", aliases: ["over brace"], keywords: ["Overbrace", "Nẹp quá mức", "over brace"], category: "structure", defaultPriority: 64, supportedInMathMode: true },
  { id: "overgroup", command: "\\overgroup", insertTemplate: "\\overgroup{\\placeholder{}}", previewLatex: "\\overgroup{AB}", labelVi: "Tập hợp lại", labelEn: "Overgroup", aliases: ["over group"], keywords: ["Overgroup", "Tập hợp lại", "over group"], category: "structure", defaultPriority: 63, supportedInMathMode: true },
  { id: "overparen", command: "\\overparen", insertTemplate: "\\overparen{\\placeholder{}}", previewLatex: "\\overparen{AB}", labelVi: "Tổng quan", labelEn: "Overparen", aliases: ["over paren"], keywords: ["Overparen", "Tổng quan", "over paren"], category: "structure", defaultPriority: 63, supportedInMathMode: true },
  { id: "overleftarrow", command: "\\overleftarrow", insertTemplate: "\\overleftarrow{\\placeholder{}}", previewLatex: "\\overleftarrow{AB}", labelVi: "Qua mũi tên trái", labelEn: "Over left arrow", aliases: ["over left arrow"], keywords: ["Over left arrow", "Qua mũi tên trái", "over left arrow"], category: "structure", defaultPriority: 62, supportedInMathMode: true },
  { id: "overrightarrow", command: "\\overrightarrow", insertTemplate: "\\overrightarrow{\\placeholder{}}", previewLatex: "\\overrightarrow{AB}", labelVi: "Qua mũi tên bên phải", labelEn: "Over right arrow", aliases: ["over right arrow"], keywords: ["Over right arrow", "Qua mũi tên bên phải", "over right arrow"], category: "structure", defaultPriority: 62, supportedInMathMode: true },
  { id: "overleftrightarrow", command: "\\overleftrightarrow", insertTemplate: "\\overleftrightarrow{\\placeholder{}}", previewLatex: "\\overleftrightarrow{AB}", labelVi: "Qua mũi tên trái phải", labelEn: "Over left-right arrow", aliases: ["over left right arrow"], keywords: ["Over left-right arrow", "Qua mũi tên trái phải", "over left right arrow"], category: "structure", defaultPriority: 61, supportedInMathMode: true },
  { id: "overleftharpoon", command: "\\overleftharpoon", insertTemplate: "\\overleftharpoon{\\placeholder{}}", previewLatex: "\\overleftharpoon{AB}", labelVi: "Cây lao phía bên trái", labelEn: "Over left harpoon", aliases: ["over left harpoon"], keywords: ["Over left harpoon", "Cây lao phía bên trái", "over left harpoon"], category: "structure", defaultPriority: 60, supportedInMathMode: true },
  { id: "overrightharpoon", command: "\\overrightharpoon", insertTemplate: "\\overrightharpoon{\\placeholder{}}", previewLatex: "\\overrightharpoon{AB}", labelVi: "Cây lao phía bên phải", labelEn: "Over right harpoon", aliases: ["over right harpoon"], keywords: ["Over right harpoon", "Cây lao phía bên phải", "over right harpoon"], category: "structure", defaultPriority: 60, supportedInMathMode: true },
  { id: "overlinesegment", command: "\\overlinesegment", insertTemplate: "\\overlinesegment{\\placeholder{}}", previewLatex: "\\overlinesegment{AB}", labelVi: "Đoạn trên đường", labelEn: "Over line segment", aliases: ["over line segment"], keywords: ["Over line segment", "Đoạn trên đường", "over line segment"], category: "structure", defaultPriority: 59, supportedInMathMode: true },
  { id: "underarc", command: "\\underarc", insertTemplate: "\\underarc{\\placeholder{}}", previewLatex: "\\underarc{AB}", labelVi: "Dưới cung", labelEn: "Under arc", aliases: ["under arc"], keywords: ["Under arc", "Dưới cung", "under arc"], category: "structure", defaultPriority: 65, supportedInMathMode: true },
  { id: "underline", command: "\\underline", insertTemplate: "\\underline{\\placeholder{}}", previewLatex: "\\underline{AB}", labelVi: "Gạch chân", labelEn: "Underline", aliases: ["under line"], keywords: ["Underline", "Gạch chân", "under line"], category: "structure", defaultPriority: 65, supportedInMathMode: true },
  { id: "underbrace", command: "\\underbrace", insertTemplate: "\\underbrace{\\placeholder{}}", previewLatex: "\\underbrace{a+b}", labelVi: "Nẹp lót", labelEn: "Underbrace", aliases: ["under brace"], keywords: ["Underbrace", "Nẹp lót", "under brace"], category: "structure", defaultPriority: 64, supportedInMathMode: true },
  { id: "undergroup", command: "\\undergroup", insertTemplate: "\\undergroup{\\placeholder{}}", previewLatex: "\\undergroup{AB}", labelVi: "Nhóm nhỏ", labelEn: "Undergroup", aliases: ["under group"], keywords: ["Undergroup", "Nhóm nhỏ", "under group"], category: "structure", defaultPriority: 63, supportedInMathMode: true },
  { id: "underparen", command: "\\underparen", insertTemplate: "\\underparen{\\placeholder{}}", previewLatex: "\\underparen{AB}", labelVi: "Đồ lót", labelEn: "Underparen", aliases: ["under paren"], keywords: ["Underparen", "Đồ lót", "under paren"], category: "structure", defaultPriority: 63, supportedInMathMode: true },
  { id: "underleftarrow", command: "\\underleftarrow", insertTemplate: "\\underleftarrow{\\placeholder{}}", previewLatex: "\\underleftarrow{AB}", labelVi: "Dưới mũi tên trái", labelEn: "Under left arrow", aliases: ["under left arrow"], keywords: ["Under left arrow", "Dưới mũi tên trái", "under left arrow"], category: "structure", defaultPriority: 62, supportedInMathMode: true },
  { id: "underrightarrow", command: "\\underrightarrow", insertTemplate: "\\underrightarrow{\\placeholder{}}", previewLatex: "\\underrightarrow{AB}", labelVi: "Dưới mũi tên phải", labelEn: "Under right arrow", aliases: ["under right arrow"], keywords: ["Under right arrow", "Dưới mũi tên phải", "under right arrow"], category: "structure", defaultPriority: 62, supportedInMathMode: true },
  { id: "underleftrightarrow", command: "\\underleftrightarrow", insertTemplate: "\\underleftrightarrow{\\placeholder{}}", previewLatex: "\\underleftrightarrow{AB}", labelVi: "Dưới mũi tên trái phải", labelEn: "Under left-right arrow", aliases: ["under left right arrow"], keywords: ["Under left-right arrow", "Dưới mũi tên trái phải", "under left right arrow"], category: "structure", defaultPriority: 61, supportedInMathMode: true },
  { id: "underlinesegment", command: "\\underlinesegment", insertTemplate: "\\underlinesegment{\\placeholder{}}", previewLatex: "\\underlinesegment{AB}", labelVi: "Đoạn dưới đường", labelEn: "Under line segment", aliases: ["under line segment"], keywords: ["Under line segment", "Đoạn dưới đường", "under line segment"], category: "structure", defaultPriority: 59, supportedInMathMode: true },

  { id: "int", command: "\\int", insertTemplate: "\\int_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}\\placeholder{}", previewLatex: "\\int_a^b f(x)\\,\\mathrm{d}x", labelVi: "Tích phân", labelEn: "Integral", aliases: ["integral"], keywords: ["Integral", "Tích phân", "integral"], category: "calculus", defaultPriority: 100, supportedInMathMode: true },
  { id: "iint", command: "\\iint", insertTemplate: "\\iint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}A", previewLatex: "\\iint_D f\\,\\mathrm{d}A", labelVi: "Tích phân kép", labelEn: "Double integral", aliases: ["double integral"], keywords: ["Double integral", "Tích phân kép", "double integral"], category: "calculus", defaultPriority: 78, supportedInMathMode: true },
  { id: "oint", command: "\\oint", insertTemplate: "\\oint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}\\placeholder{}", previewLatex: "\\oint_C \\mathbf{F}\\cdot\\mathrm{d}\\mathbf{r}", labelVi: "Tích phân đường viền", labelEn: "Contour integral", aliases: ["contour integral"], keywords: ["Contour integral", "Tích phân đường viền", "contour integral"], category: "calculus", defaultPriority: 76, supportedInMathMode: true },
  { id: "sum", command: "\\sum", insertTemplate: "\\sum_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", previewLatex: "\\sum_{i=1}^{n} a_i", labelVi: "Tổng kết", labelEn: "Summation", aliases: ["summation"], keywords: ["Summation", "Tổng kết", "summation"], category: "calculus", defaultPriority: 96, supportedInMathMode: true },
  { id: "prod", command: "\\prod", insertTemplate: "\\prod_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", previewLatex: "\\prod_{i=1}^{n} a_i", labelVi: "Sản phẩm", labelEn: "Product", aliases: ["product"], keywords: ["Product", "Sản phẩm", "product"], category: "calculus", defaultPriority: 79, supportedInMathMode: true },
  { id: "lim", command: "\\lim", insertTemplate: "\\lim_{\\placeholder{}\\to\\placeholder{}} \\placeholder{}", previewLatex: "\\lim_{x\\to 0} f(x)", labelVi: "Giới hạn", labelEn: "Limit", aliases: ["limit"], keywords: ["Limit", "Giới hạn", "limit"], category: "calculus", defaultPriority: 92, supportedInMathMode: true },
  { id: "partial", command: "\\partial", insertTemplate: "\\frac{\\partial \\placeholder{}}{\\partial \\placeholder{}}", previewLatex: "\\frac{\\partial f}{\\partial x}", labelVi: "Đạo hàm riêng phần", labelEn: "Partial derivative", aliases: ["partial", "derivative"], keywords: ["Partial derivative", "Đạo hàm riêng phần", "partial", "derivative"], category: "calculus", defaultPriority: 86, supportedInMathMode: true },
  { id: "nabla", command: "\\nabla", insertTemplate: "\\nabla", previewLatex: "\\nabla f", labelVi: "Nabla", labelEn: "Nabla", aliases: ["gradient", "del"], keywords: ["Nabla", "Nabla", "gradient", "del"], category: "calculus", defaultPriority: 74, supportedInMathMode: true },
  { id: "infty", command: "\\infty", insertTemplate: "\\infty", previewLatex: "\\infty", labelVi: "Vô cực", labelEn: "Infinity", aliases: ["infinity"], keywords: ["Infinity", "Vô cực", "infinity"], category: "calculus", defaultPriority: 88, supportedInMathMode: true },

  { id: "matrix2", command: "\\begin{bmatrix}", insertTemplate: "\\begin{bmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{bmatrix}", previewLatex: "\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}", labelVi: "Ma trận 2×2", labelEn: "2×2 matrix", aliases: ["matrix", "bmatrix"], keywords: ["2×2 matrix", "Ma trận 2×2", "matrix", "bmatrix"], category: "matrix", defaultPriority: 100, supportedInMathMode: true },
  { id: "matrix3", command: "\\begin{bmatrix}", insertTemplate: "\\begin{bmatrix}\\placeholder{} & \\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{} & \\placeholder{}\\end{bmatrix}", previewLatex: "\\begin{bmatrix}a&b&c\\\\d&e&f\\\\g&h&i\\end{bmatrix}", labelVi: "Ma trận 3×3", labelEn: "3×3 matrix", aliases: ["matrix", "bmatrix"], keywords: ["3×3 matrix", "Ma trận 3×3", "matrix", "bmatrix"], category: "matrix", defaultPriority: 90, supportedInMathMode: true },
  { id: "pmatrix2", command: "\\begin{pmatrix}", insertTemplate: "\\begin{pmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{pmatrix}", previewLatex: "\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}", labelVi: "Ma trận trong ngoặc đơn", labelEn: "Parenthesized matrix", aliases: ["pmatrix"], keywords: ["Parenthesized matrix", "Ma trận trong ngoặc đơn", "pmatrix"], category: "matrix", defaultPriority: 88, supportedInMathMode: true },
  { id: "determinant", command: "\\begin{vmatrix}", insertTemplate: "\\begin{vmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{vmatrix}", previewLatex: "\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}", labelVi: "Định thức", labelEn: "Determinant", aliases: ["det", "determinant"], keywords: ["Determinant", "Định thức", "det", "determinant"], category: "matrix", defaultPriority: 87, supportedInMathMode: true },
  { id: "vector", command: "\\vec", insertTemplate: "\\vec{\\placeholder{}}", previewLatex: "\\vec{v}", labelVi: "Vectơ", labelEn: "Vector", aliases: ["vector"], keywords: ["Vector", "Vectơ", "vector"], category: "matrix", defaultPriority: 84, supportedInMathMode: true },
  { id: "boldsymbol", command: "\\mathbf", insertTemplate: "\\mathbf{\\placeholder{}}", previewLatex: "\\mathbf{ABC}", labelVi: "Toán đậm nét", labelEn: "Bold math", aliases: ["bold", "mathbf"], keywords: ["Bold math", "Toán đậm nét", "bold", "mathbf"], category: "matrix", defaultPriority: 82, supportedInMathMode: true },
  { id: "blackboard-bold", command: "\\mathbb", insertTemplate: "\\mathbb{\\placeholder{}}", previewLatex: "\\mathbb{ABC}", labelVi: "Bảng in đậm", labelEn: "Blackboard bold", aliases: ["blackboard", "mathbb"], keywords: ["Blackboard bold", "Bảng in đậm", "blackboard", "mathbb"], category: "matrix", defaultPriority: 84, supportedInMathMode: true },
  { id: "math-italic", command: "\\mathit", insertTemplate: "\\mathit{\\placeholder{}}", previewLatex: "\\mathit{ABC}", labelVi: "Toán in nghiêng", labelEn: "Math italic", aliases: ["italic", "mathit"], keywords: ["Math italic", "Toán in nghiêng", "italic", "mathit"], category: "matrix", defaultPriority: 76, supportedInMathMode: true },
  { id: "math-roman", command: "\\mathrm", insertTemplate: "\\mathrm{\\placeholder{}}", previewLatex: "\\mathrm{ABC}", labelVi: "La Mã toán học", labelEn: "Math roman", aliases: ["roman", "mathrm"], keywords: ["Math roman", "La Mã toán học", "roman", "mathrm"], category: "matrix", defaultPriority: 78, supportedInMathMode: true },
  { id: "math-sans", command: "\\mathsf", insertTemplate: "\\mathsf{\\placeholder{}}", previewLatex: "\\mathsf{ABC}", labelVi: "Toán sans serif", labelEn: "Math sans serif", aliases: ["sans", "mathsf"], keywords: ["Math sans serif", "Toán sans serif", "sans", "mathsf"], category: "matrix", defaultPriority: 70, supportedInMathMode: true },
  { id: "math-typewriter", command: "\\mathtt", insertTemplate: "\\mathtt{\\placeholder{}}", previewLatex: "\\mathtt{ABC}", labelVi: "Máy đánh chữ toán học", labelEn: "Math typewriter", aliases: ["typewriter", "mathtt"], keywords: ["Math typewriter", "Máy đánh chữ toán học", "typewriter", "mathtt"], category: "matrix", defaultPriority: 68, supportedInMathMode: true },
  { id: "math-calligraphic", command: "\\mathcal", insertTemplate: "\\mathcal{\\placeholder{}}", previewLatex: "\\mathcal{ABC}", labelVi: "Thư pháp viết hoa", labelEn: "Uppercase calligraphic", aliases: ["calligraphic", "mathcal"], keywords: ["Uppercase calligraphic", "Thư pháp viết hoa", "calligraphic", "mathcal"], category: "matrix", defaultPriority: 74, supportedInMathMode: true },
  { id: "math-script", command: "\\mathscr", insertTemplate: "\\mathscr{\\placeholder{}}", previewLatex: "\\mathscr{gG}", labelVi: "Kịch bản toán học", labelEn: "Math script", aliases: ["script", "mathscr"], keywords: ["Math script", "Kịch bản toán học", "script", "mathscr"], category: "matrix", defaultPriority: 75, supportedInMathMode: true },
  { id: "math-fraktur", command: "\\mathfrak", insertTemplate: "\\mathfrak{\\placeholder{}}", previewLatex: "\\mathfrak{ABC}", labelVi: "Fraktur Toán học", labelEn: "Math Fraktur", aliases: ["fraktur", "mathfrak"], keywords: ["Math Fraktur", "Fraktur Toán học", "fraktur", "mathfrak"], category: "matrix", defaultPriority: 72, supportedInMathMode: true },
  { id: "bold-symbol", command: "\\boldsymbol", insertTemplate: "\\boldsymbol{\\placeholder{}}", previewLatex: "\\boldsymbol{\\alpha A}", labelVi: "Ký hiệu in đậm", labelEn: "Bold symbol", aliases: ["bold symbol", "boldsymbol"], keywords: ["Bold symbol", "Ký hiệu in đậm", "bold symbol", "boldsymbol"], category: "matrix", defaultPriority: 75, supportedInMathMode: true },
  { id: "bm-bold-symbol", command: "\\bm", insertTemplate: "\\bm{\\placeholder{}}", previewLatex: "\\bm{\\alpha A}", labelVi: "BM đậm tính toán", labelEn: "BM bold math", aliases: ["bm", "bold math italic"], keywords: ["BM bold math", "BM đậm tính toán", "bm", "bold math italic"], category: "matrix", defaultPriority: 76, supportedInMathMode: true },
  { id: "math-bold-italic", command: "\\mathbfit", insertTemplate: "\\mathbfit{\\placeholder{}}", previewLatex: "\\mathbfit{ABC}", labelVi: "Toán in nghiêng đậm", labelEn: "Bold italic math", aliases: ["bold italic", "mathbfit"], keywords: ["Bold italic math", "Toán in nghiêng đậm", "bold italic", "mathbfit"], category: "matrix", defaultPriority: 73, supportedInMathMode: true },
  { id: "math-normal", command: "\\mathnormal", insertTemplate: "\\mathnormal{\\placeholder{}}", previewLatex: "\\mathnormal{ABC}", labelVi: "Toán thông thường", labelEn: "Normal math", aliases: ["normal math", "mathnormal"], keywords: ["Normal math", "Toán thông thường", "normal math", "mathnormal"], category: "matrix", defaultPriority: 64, supportedInMathMode: true },
  { id: "math-operator", command: "\\mathop", insertTemplate: "\\mathop{\\placeholder{}}", previewLatex: "\\mathop{f(x)}", labelVi: "Toán tử toán học", labelEn: "Math operator", aliases: ["operator", "mathop"], keywords: ["Math operator", "Toán tử toán học", "operator", "mathop"], category: "matrix", defaultPriority: 66, supportedInMathMode: true },

  { id: "alpha", command: "\\alpha", insertTemplate: "\\alpha", previewLatex: "\\alpha", labelVi: "Alpha", labelEn: "Alpha", aliases: ["alpha"], keywords: ["Alpha", "Alpha", "alpha"], category: "greek", defaultPriority: 100, supportedInMathMode: true },
  { id: "beta", command: "\\beta", insertTemplate: "\\beta", previewLatex: "\\beta", labelVi: "Beta", labelEn: "Beta", aliases: ["beta"], keywords: ["Beta", "Beta", "beta"], category: "greek", defaultPriority: 98, supportedInMathMode: true },
  { id: "gamma", command: "\\gamma", insertTemplate: "\\gamma", previewLatex: "\\gamma", labelVi: "Gamma", labelEn: "Gamma", aliases: ["gamma"], keywords: ["Gamma", "Gamma", "gamma"], category: "greek", defaultPriority: 96, supportedInMathMode: true },
  { id: "delta", command: "\\delta", insertTemplate: "\\delta", previewLatex: "\\delta", labelVi: "Đồng bằng", labelEn: "Delta", aliases: ["delta"], keywords: ["Delta", "Đồng bằng", "delta"], category: "greek", defaultPriority: 94, supportedInMathMode: true },
  { id: "theta", command: "\\theta", insertTemplate: "\\theta", previewLatex: "\\theta", labelVi: "Theta", labelEn: "Theta", aliases: ["theta"], keywords: ["Theta", "Theta", "theta"], category: "greek", defaultPriority: 92, supportedInMathMode: true },
  { id: "lambda", command: "\\lambda", insertTemplate: "\\lambda", previewLatex: "\\lambda", labelVi: "Lambda", labelEn: "Lambda", aliases: ["lambda"], keywords: ["Lambda", "Lambda", "lambda"], category: "greek", defaultPriority: 90, supportedInMathMode: true },
  { id: "mu", command: "\\mu", insertTemplate: "\\mu", previewLatex: "\\mu", labelVi: "Mu", labelEn: "Mu", aliases: ["mu"], keywords: ["Mu", "Mu", "mu"], category: "greek", defaultPriority: 88, supportedInMathMode: true },
  { id: "pi", command: "\\pi", insertTemplate: "\\pi", previewLatex: "\\pi", labelVi: "Pi", labelEn: "Pi", aliases: ["pi"], keywords: ["Pi", "Pi", "pi"], category: "greek", defaultPriority: 100, supportedInMathMode: true },
  { id: "sigma", command: "\\sigma", insertTemplate: "\\sigma", previewLatex: "\\sigma", labelVi: "Sigma", labelEn: "Sigma", aliases: ["sigma"], keywords: ["Sigma", "Sigma", "sigma"], category: "greek", defaultPriority: 86, supportedInMathMode: true },
  { id: "omega", command: "\\omega", insertTemplate: "\\omega", previewLatex: "\\omega", labelVi: "Omega", labelEn: "Omega", aliases: ["omega"], keywords: ["Omega", "Omega", "omega"], category: "greek", defaultPriority: 84, supportedInMathMode: true },

  { id: "equal", command: "=", insertTemplate: "=", previewLatex: "=", labelVi: "Bằng", labelEn: "Equals", aliases: ["equal"], keywords: ["Equals", "Bằng", "equal"], category: "relation", defaultPriority: 100, supportedInMathMode: true },
  { id: "neq", command: "\\neq", insertTemplate: "\\neq", previewLatex: "\\neq", labelVi: "Không bằng", labelEn: "Not equal", aliases: ["not equal"], keywords: ["Not equal", "Không bằng", "not equal"], category: "relation", defaultPriority: 96, supportedInMathMode: true },
  { id: "approx", command: "\\approx", insertTemplate: "\\approx", previewLatex: "\\approx", labelVi: "Khoảng", labelEn: "Approximately", aliases: ["approximately"], keywords: ["Approximately", "Khoảng", "approximately"], category: "relation", defaultPriority: 92, supportedInMathMode: true },
  { id: "leq", command: "\\leq", insertTemplate: "\\leq", previewLatex: "\\leq", labelVi: "Nhỏ hơn hoặc bằng", labelEn: "Less or equal", aliases: ["less equal"], keywords: ["Less or equal", "Nhỏ hơn hoặc bằng", "less equal"], category: "relation", defaultPriority: 90, supportedInMathMode: true },
  { id: "geq", command: "\\geq", insertTemplate: "\\geq", previewLatex: "\\geq", labelVi: "Lớn hơn hoặc bằng", labelEn: "Greater or equal", aliases: ["greater equal"], keywords: ["Greater or equal", "Lớn hơn hoặc bằng", "greater equal"], category: "relation", defaultPriority: 90, supportedInMathMode: true },
  { id: "propto", command: "\\propto", insertTemplate: "\\propto", previewLatex: "\\propto", labelVi: "Tỉ lệ thuận với", labelEn: "Proportional to", aliases: ["proportional"], keywords: ["Proportional to", "Tỉ lệ thuận với", "proportional"], category: "relation", defaultPriority: 82, supportedInMathMode: true },
  { id: "times", command: "\\times", insertTemplate: "\\times", previewLatex: "\\times", labelVi: "Phép nhân", labelEn: "Multiplication", aliases: ["times", "multiply", "multiplication"], keywords: ["Multiplication", "Phép nhân", "times", "multiply", "multiplication"], category: "relation", defaultPriority: 98, supportedInMathMode: true },
  { id: "div", command: "\\div", insertTemplate: "\\div", previewLatex: "\\div", labelVi: "Phòng", labelEn: "Division", aliases: ["divide", "division"], keywords: ["Division", "Phòng", "divide", "division"], category: "relation", defaultPriority: 97, supportedInMathMode: true },

  { id: "in", command: "\\in", insertTemplate: "\\in", previewLatex: "\\in", labelVi: "Phần tử của", labelEn: "Element of", aliases: ["element"], keywords: ["Element of", "Phần tử của", "element"], category: "set", defaultPriority: 100, supportedInMathMode: true },
  { id: "notin", command: "\\notin", insertTemplate: "\\notin", previewLatex: "\\notin", labelVi: "Không phải là một phần tử", labelEn: "Not an element", aliases: ["not element"], keywords: ["Not an element", "Không phải là một phần tử", "not element"], category: "set", defaultPriority: 92, supportedInMathMode: true },
  { id: "subset", command: "\\subset", insertTemplate: "\\subset", previewLatex: "\\subset", labelVi: "Tập con", labelEn: "Subset", aliases: ["subset"], keywords: ["Subset", "Tập con", "subset"], category: "set", defaultPriority: 90, supportedInMathMode: true },
  { id: "cup", command: "\\cup", insertTemplate: "\\cup", previewLatex: "\\cup", labelVi: "Đoàn", labelEn: "Union", aliases: ["union"], keywords: ["Union", "Đoàn", "union"], category: "set", defaultPriority: 88, supportedInMathMode: true },
  { id: "cap", command: "\\cap", insertTemplate: "\\cap", previewLatex: "\\cap", labelVi: "Nút giao", labelEn: "Intersection", aliases: ["intersection"], keywords: ["Intersection", "Nút giao", "intersection"], category: "set", defaultPriority: 88, supportedInMathMode: true },
  { id: "forall", command: "\\forall", insertTemplate: "\\forall", previewLatex: "\\forall", labelVi: "Dành cho tất cả", labelEn: "For all", aliases: ["for all"], keywords: ["For all", "Dành cho tất cả", "for all"], category: "set", defaultPriority: 86, supportedInMathMode: true },
  { id: "exists", command: "\\exists", insertTemplate: "\\exists", previewLatex: "\\exists", labelVi: "Tồn tại", labelEn: "Exists", aliases: ["exists"], keywords: ["Exists", "Tồn tại", "exists"], category: "set", defaultPriority: 84, supportedInMathMode: true },

  { id: "to", command: "\\to", insertTemplate: "\\to", previewLatex: "\\to", labelVi: "Tới", labelEn: "To", aliases: ["to", "right arrow"], keywords: ["To", "Tới", "to", "right arrow"], category: "arrow", defaultPriority: 100, supportedInMathMode: true },
  { id: "rightarrow", command: "\\rightarrow", insertTemplate: "\\rightarrow", previewLatex: "\\rightarrow", labelVi: "Mũi tên phải", labelEn: "Right arrow", aliases: ["right arrow"], keywords: ["Right arrow", "Mũi tên phải", "right arrow"], category: "arrow", defaultPriority: 96, supportedInMathMode: true },
  { id: "leftarrow", command: "\\leftarrow", insertTemplate: "\\leftarrow", previewLatex: "\\leftarrow", labelVi: "Mũi tên trái", labelEn: "Left arrow", aliases: ["left arrow"], keywords: ["Left arrow", "Mũi tên trái", "left arrow"], category: "arrow", defaultPriority: 94, supportedInMathMode: true },
  { id: "leftrightarrow", command: "\\leftrightarrow", insertTemplate: "\\leftrightarrow", previewLatex: "\\leftrightarrow", labelVi: "Cả hai chiều", labelEn: "Both ways", aliases: ["both arrow"], keywords: ["Both ways", "Cả hai chiều", "both arrow"], category: "arrow", defaultPriority: 88, supportedInMathMode: true },
  { id: "Rightarrow", command: "\\Rightarrow", insertTemplate: "\\Rightarrow", previewLatex: "\\Rightarrow", labelVi: "Ngụ ý", labelEn: "Implies", aliases: ["implies"], keywords: ["Implies", "Ngụ ý", "implies"], category: "arrow", defaultPriority: 90, supportedInMathMode: true },

  { id: "hbar", command: "\\hbar", insertTemplate: "\\hbar", previewLatex: "\\hbar", labelVi: "Hằng số Planck giảm", labelEn: "Reduced Planck constant", aliases: ["hbar", "planck"], keywords: ["Reduced Planck constant", "Hằng số Planck giảm", "hbar", "planck"], category: "physics", defaultPriority: 100, supportedInMathMode: true },
  { id: "dd", command: "\\mathrm{d}", insertTemplate: "\\mathrm{d}\\placeholder{}", previewLatex: "\\mathrm{d}x", labelVi: "Vi sai", labelEn: "Differential", aliases: ["differential"], keywords: ["Differential", "Vi sai", "differential"], category: "physics", defaultPriority: 96, supportedInMathMode: true },
  { id: "bra", command: "\\langle", insertTemplate: "\\langle\\placeholder{}|", previewLatex: "\\langle\\psi|", labelVi: "Áo ngực", labelEn: "Bra", aliases: ["bra"], keywords: ["Bra", "Áo ngực", "bra"], category: "physics", defaultPriority: 92, supportedInMathMode: true },
  { id: "ket", command: "\\rangle", insertTemplate: "|\\placeholder{}\\rangle", previewLatex: "|\\psi\\rangle", labelVi: "Kết", labelEn: "Ket", aliases: ["ket"], keywords: ["Ket", "Kết", "ket"], category: "physics", defaultPriority: 92, supportedInMathMode: true },
  { id: "degree", command: "^\\circ", insertTemplate: "^{\\circ}", previewLatex: "30^{\\circ}", labelVi: "Bằng cấp", labelEn: "Degree", aliases: ["degree"], keywords: ["Degree", "Bằng cấp", "degree"], category: "physics", defaultPriority: 86, supportedInMathMode: true },
];

export const commandRegistry: LatexCommand[] = [
  ...baseCommandRegistry,
  ...additionalCommands,
  ...latestSharedCommands,
];

export const categoryLabels: Record<string, string> = {
  common: "Thông dụng",
  structure: "Cấu trúc",
  calculus: "Giải tích",
  matrix: "Ma trận",
  greek: "Chữ cái Hy Lạp",
  relation: "Quan hệ",
  set: "Tập hợp và logic",
  arrow: "Mũi tên",
  physics: "Vật lý",
};

export const categoryLabelsEn: Record<string, string> = {
  common: "Common",
  structure: "Structures",
  calculus: "Calculus",
  matrix: "Matrices",
  greek: "Greek",
  relation: "Relations",
  set: "Sets & Logic",
  arrow: "Arrows",
  physics: "Physics",
};

export const commonCommandIds = [
  "frac",
  "sqrt",
  "power",
  "subscript",
  "hat",
  "tilde",
  "parentheses",
  "absolute",
  "intplain",
  "int",
  "iint",
  "oint",
  "sum",
  "prod",
  "lim",
  "partial",
  "derivative",
  "nabla",
  "infty",
  "matrix2",
  "cases",
  "vector",
  "alpha",
  "beta",
  "gamma",
  "theta",
  "lambda",
  "mu",
  "pi",
  "sigma",
  "omega",
  "delta",
  "equal",
  "neq",
  "approx",
  "leq",
  "geq",
  "propto",
  "times",
  "div",
  "in",
  "subset",
  "rightarrow",
  "forall",
  "exists",
];

export const calculusCommandIds = [
  "intplain",
  "int",
  "iint-bounds",
  "iiint-bounds",
  "oint-bounds",
  "lineintegral",
  "iint",
  "surfaceintegral",
  "iiint",
  "volumeintegral",
  "oint",
  "closed-surface-integral",
  "closed-volume-integral",
  "sum",
  "sum-finite",
  "series",
  "prod",
  "prod-finite",
  "productseries",
  "coproduct",
  "lim",
  "lim-infty",
  "lim-left",
  "lim-right",
  "derivative",
  "secondderivative",
  "partial",
  "partialsecond",
  "mixedpartial",
  "evalbar",
  "nabla",
  "infty",
  "ln",
  "log",
  "exp",
  "sin",
  "cos",
  "tan",
];
