import type { LatexCommand } from "../types/command";

function command(
  id: string,
  value: string,
  category: LatexCommand["category"],
  labelVi: string,
  labelEn: string,
  priority = 70,
): LatexCommand {
  return {
    id,
    command: value,
    insertTemplate: value,
    previewLatex: value,
    labelVi,
    labelEn,
    aliases: [],
    keywords: [labelVi, labelEn],
    category,
    defaultPriority: priority,
    supportedInMathMode: true,
  };
}

export const latestSharedCommands: LatexCommand[] = [
  command(
    "fint",
    "\\fint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "Tích phân trung bình",
    "Average integral",
    84,
  ),
  command(
    "dashint",
    "\\dashint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "Tích phân nét đứt",
    "Dashed integral",
    83,
  ),
  command(
    "ddashint",
    "\\ddashint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "Tích phân nét đôi",
    "Double-dashed integral",
    82,
  ),
  command(
    "oiint",
    "\\oiint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "Tích phân kép đóng",
    "Closed double integral",
    82,
  ),
  command(
    "oiiint",
    "\\oiiint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "Tích phân ba đóng",
    "Closed triple integral",
    81,
  ),
  command(
    "ointctrclockwise",
    "\\ointctrclockwise_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "Tích phân đường viền ngược chiều kim đồng hồ",
    "Counterclockwise contour integral",
    80,
  ),
  command(
    "varointclockwise",
    "\\varointclockwise_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "Tích phân đường viền theo chiều kim đồng hồ",
    "Clockwise contour integral",
    79,
  ),
  command(
    "varointctrclockwise",
    "\\varointctrclockwise_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}",
    "calculus",
    "Tích phân đường viền biến thể ngược chiều kim đồng hồ",
    "Counterclockwise variant contour integral",
    79,
  ),
  command(
    "bigcap-limits",
    "\\bigcap_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Nút giao thông lớn có giới hạn",
    "Big intersection with limits",
  ),
  command(
    "bigcup-limits",
    "\\bigcup_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Liên minh lớn có giới hạn",
    "Big union with limits",
  ),
  command(
    "bigsqcup-limits",
    "\\bigsqcup_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Liên minh rời rạc có giới hạn",
    "Disjoint union with limits",
  ),
  command(
    "bigvee-limits",
    "\\bigvee_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Logic lớn HOẶC có giới hạn",
    "Big logical OR with limits",
  ),
  command(
    "bigwedge-limits",
    "\\bigwedge_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Logic lớn VÀ có giới hạn",
    "Big logical AND with limits",
  ),
  command(
    "bigodot-limits",
    "\\bigodot_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Dấu chấm lớn có giới hạn",
    "Big odot with limits",
  ),
  command(
    "bigoplus-limits",
    "\\bigoplus_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Tổng trực tiếp có giới hạn",
    "Direct sum with limits",
  ),
  command(
    "bigotimes-limits",
    "\\bigotimes_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Sản phẩm tensor có giới hạn",
    "Tensor product with limits",
  ),
  command(
    "biguplus-limits",
    "\\biguplus_{i=1}^{n} \\placeholder{}",
    "calculus",
    "Liên kết nhiều bộ có giới hạn",
    "Multiset union with limits",
  ),
  command(
    "cases-three",
    "\\begin{cases}\\placeholder{}\\\\\\placeholder{}\\\\\\placeholder{}\\end{cases}",
    "structure",
    "Thùng ba hàng",
    "Three-row cases",
    76,
  ),
  command(
    "matrix-dots",
    "\\begin{bmatrix}\\placeholder{}&\\cdots&\\placeholder{}\\\\\\vdots&\\ddots&\\vdots\\\\\\placeholder{}&\\cdots&\\placeholder{}\\end{bmatrix}",
    "matrix",
    "Ma trận có dấu chấm",
    "Matrix with dots",
    75,
  ),
  command(
    "diagonal-matrix",
    "\\begin{bmatrix}\\placeholder{}&0&\\cdots\\\\0&\\placeholder{}&\\ddots\\\\\\vdots&\\ddots&\\placeholder{}\\end{bmatrix}",
    "matrix",
    "Ma trận đường chéo",
    "Diagonal matrix",
    76,
  ),
  command(
    "augmented-matrix",
    "\\left[\\begin{array}{cc|c}\\placeholder{}&\\placeholder{}&\\placeholder{}\\\\\\placeholder{}&\\placeholder{}&\\placeholder{}\\end{array}\\right]",
    "matrix",
    "Ma trận mở rộng",
    "Augmented matrix",
    74,
  ),
  command(
    "block-matrix",
    "\\begin{bmatrix}\\placeholder{}&\\placeholder{}\\\\\\placeholder{}&\\placeholder{}\\end{bmatrix}",
    "matrix",
    "Ma trận khối",
    "Block matrix",
    73,
  ),
];
