import type { CommandCategory, LatexCommand } from "../types/command";

const makeCommand = (
  id: string,
  command: string,
  insertTemplate: string,
  previewLatex: string,
  labelVi: string,
  labelEn: string,
  category: CommandCategory,
  defaultPriority = 72,
  aliases: string[] = [],
  keywords: string[] = [],
): LatexCommand => ({
  id,
  command,
  insertTemplate,
  previewLatex,
  labelVi,
  labelEn,
  aliases,
  keywords,
  category,
  defaultPriority,
  supportedInMathMode: true,
});

const complexCommands: LatexCommand[] = [
  // 对现有选区添加上标、下标或上下限
  makeCommand("scripts", "_{}^{}", "\\placeholder{}_{\\placeholder{}}^{\\placeholder{}}", "X_{a}^{b}", "Thêm giới hạn trên/dưới", "Add upper/lower limits", "structure", 96, ["limits", "scripts"], ["Add upper/lower limits", "Thêm giới hạn trên/dưới"]),
  makeCommand("lower-script", "_{}", "\\placeholder{}_{\\placeholder{}}", "X_{a}", "Thêm giới hạn dưới", "Add lower limit", "structure", 92, ["lower limit", "subscript"], ["Add lower limit", "Thêm giới hạn dưới"]),
  makeCommand("upper-script", "^{}", "\\placeholder{}^{\\placeholder{}}", "X^{b}", "Thêm giới hạn trên", "Add upper limit", "structure", 92, ["upper limit", "superscript"], ["Add upper limit", "Thêm giới hạn trên"]),

  // 基础结构
  makeCommand("smallfrac", "\\tfrac", "\\tfrac{\\placeholder{}}{\\placeholder{}}", "\\tfrac{a}{b}", "Phân đoạn văn bản", "Text fraction", "structure", 79, ["tfrac"], ["Text fraction", "Phân đoạn văn bản"]),
  makeCommand("displayfrac", "\\dfrac", "\\dfrac{\\placeholder{}}{\\placeholder{}}", "\\dfrac{a}{b}", "Hiển thị phân số", "Display fraction", "structure", 78, ["dfrac"], ["Display fraction", "Hiển thị phân số"]),
  makeCommand("brackets", "\\left[", "\\left[\\placeholder{}\\right]", "\\left[x\\right]", "Chân đế", "Brackets", "structure", 81, ["square brackets"], ["Brackets", "Chân đế"]),
  makeCommand("braces", "\\left\\{", "\\left\\{\\placeholder{}\\right\\}", "\\left\\{x\\right\\}", "Niềng răng", "Braces", "structure", 80, ["curly braces"], ["Braces", "Niềng răng"]),
  makeCommand("anglebrackets", "\\langle", "\\left\\langle\\placeholder{}\\right\\rangle", "\\langle x\\rangle", "Giá đỡ góc", "Angle brackets", "structure", 77, ["angle brackets"], ["Angle brackets", "Giá đỡ góc"]),
  makeCommand("floor", "\\lfloor", "\\left\\lfloor\\placeholder{}\\right\\rfloor", "\\lfloor x\\rfloor", "Tầng", "Floor", "structure", 76, ["floor"], ["Floor", "Tầng"]),
  makeCommand("ceil", "\\lceil", "\\left\\lceil\\placeholder{}\\right\\rceil", "\\lceil x\\rceil", "Trần nhà", "Ceiling", "structure", 76, ["ceil", "ceiling"], ["Ceiling", "Trần nhà"]),
  makeCommand("overline", "\\overline", "\\overline{\\placeholder{}}", "\\overline{x}", "Nội dung", "Overline", "structure", 75, ["bar", "overline"], ["Overline", "Nội dung"]),
  makeCommand("hat", "\\hat", "\\hat{\\placeholder{}}", "\\hat{x}", "Giọng mũ", "Hat accent", "structure", 84, ["hat"], ["Hat accent", "Giọng mũ"]),
  makeCommand("widehat", "\\widehat", "\\widehat{\\placeholder{}}", "\\widehat{ABC}", "Mũ rộng", "Wide hat", "structure", 78, ["wide hat"], ["Wide hat", "Mũ rộng"]),
  makeCommand("tilde", "\\tilde", "\\tilde{\\placeholder{}}", "\\tilde{x}", "Dấu ngã", "Tilde accent", "structure", 83, ["tilde"], ["Tilde accent", "Dấu ngã"]),
  makeCommand("widetilde", "\\widetilde", "\\widetilde{\\placeholder{}}", "\\widetilde{ABC}", "Dấu ngã rộng", "Wide tilde", "structure", 77, ["wide tilde"], ["Wide tilde", "Dấu ngã rộng"]),
  makeCommand("dotaccent", "\\dot", "\\dot{\\placeholder{}}", "\\dot{x}", "Dấu chấm", "Dot accent", "structure", 80, ["dot"], ["Dot accent", "Dấu chấm"]),
  makeCommand("ddotaccent", "\\ddot", "\\ddot{\\placeholder{}}", "\\ddot{x}", "Dấu hai chấm", "Double-dot accent", "structure", 79, ["double dot", "ddot"], ["Double-dot accent", "Dấu hai chấm"]),
  makeCommand("checkaccent", "\\check", "\\check{\\placeholder{}}", "\\check{x}", "Kiểm tra giọng", "Check accent", "structure", 73, ["check accent"], ["Check accent", "Kiểm tra giọng"]),
  makeCommand("breveaccent", "\\breve", "\\breve{\\placeholder{}}", "\\breve{x}", "Giọng Breve", "Breve accent", "structure", 72, ["breve"], ["Breve accent", "Giọng Breve"]),
  makeCommand("acuteaccent", "\\acute", "\\acute{\\placeholder{}}", "\\acute{x}", "Giọng cấp tính", "Acute accent", "structure", 71, ["acute"], ["Acute accent", "Giọng cấp tính"]),
  makeCommand("graveaccent", "\\grave", "\\grave{\\placeholder{}}", "\\grave{x}", "Giọng nghiêm túc", "Grave accent", "structure", 70, ["grave"], ["Grave accent", "Giọng nghiêm túc"]),
  makeCommand("ringaccent", "\\mathring", "\\mathring{\\placeholder{}}", "\\mathring{x}", "Giọng chuông", "Ring accent", "structure", 69, ["ring accent"], ["Ring accent", "Giọng chuông"]),
  makeCommand("overrightarrow", "\\overrightarrow", "\\overrightarrow{\\placeholder{}}", "\\overrightarrow{AB}", "Mũi tên qua phải", "Over-arrow right", "structure", 77, ["over arrow"], ["Over-arrow right", "Mũi tên qua phải"]),
  makeCommand("overleftarrow", "\\overleftarrow", "\\overleftarrow{\\placeholder{}}", "\\overleftarrow{AB}", "Mũi tên qua trái", "Over-arrow left", "structure", 74, ["over left arrow"], ["Over-arrow left", "Mũi tên qua trái"]),
  makeCommand("underline", "\\underline", "\\underline{\\placeholder{}}", "\\underline{x}", "Gạch chân", "Underline", "structure", 73, ["underline"], ["Underline", "Gạch chân"]),
  makeCommand("overbrace", "\\overbrace", "\\overbrace{\\placeholder{}}^{\\placeholder{}}", "\\overbrace{a+\\cdots+a}^{n}", "Nẹp quá mức", "Overbrace", "structure", 72, ["overbrace"], ["Overbrace", "Nẹp quá mức"]),
  makeCommand("underbrace", "\\underbrace", "\\underbrace{\\placeholder{}}_{\\placeholder{}}", "\\underbrace{a+\\cdots+a}_{n}", "Nẹp lót", "Underbrace", "structure", 72, ["underbrace"], ["Underbrace", "Nẹp lót"]),
  makeCommand("cases", "\\begin{cases}", "\\begin{cases}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{cases}", "f(x)=\\begin{cases}x&x>0\\\\0&x\\leq0\\end{cases}", "Vỏ", "Cases", "structure", 85, ["cases", "piecewise"], ["Cases", "Vỏ"]),
  makeCommand("boxed", "\\boxed", "\\boxed{\\placeholder{}}", "\\boxed{x}", "Đóng hộp", "Boxed", "structure", 70, ["boxed", "box"], ["Boxed", "Đóng hộp"]),
  makeCommand("left-parenthesis-only", "\\left(", "\\left(\\placeholder{}\\right.", "\\left(x\\right.", "Chỉ còn lại dấu ngoặc đơn", "Left parenthesis only", "structure", 68, ["left parenthesis"], ["Left parenthesis only", "Chỉ còn lại dấu ngoặc đơn"]),
  makeCommand("right-parenthesis-only", "\\right)", "\\left.\\placeholder{}\\right)", "\\left.x\\right)", "Chỉ có dấu ngoặc đơn bên phải", "Right parenthesis only", "structure", 68, ["right parenthesis"], ["Right parenthesis only", "Chỉ có dấu ngoặc đơn bên phải"]),
  makeCommand("left-bracket-only", "\\left[", "\\left[\\placeholder{}\\right.", "\\left[x\\right.", "Chỉ dấu ngoặc trái", "Left bracket only", "structure", 67, ["left bracket"], ["Left bracket only", "Chỉ dấu ngoặc trái"]),
  makeCommand("right-bracket-only", "\\right]", "\\left.\\placeholder{}\\right]", "\\left.x\\right]", "Chỉ khung bên phải", "Right bracket only", "structure", 67, ["right bracket"], ["Right bracket only", "Chỉ khung bên phải"]),
  makeCommand("left-brace-only", "\\left\\{", "\\left\\{\\placeholder{}\\right.", "\\left\\{x\\right.", "Chỉ nẹp trái", "Left brace only", "structure", 67, ["left brace"], ["Left brace only", "Chỉ nẹp trái"]),
  makeCommand("right-brace-only", "\\right\\}", "\\left.\\placeholder{}\\right\\}", "\\left.x\\right\\}", "Chỉ nẹp bên phải", "Right brace only", "structure", 67, ["right brace"], ["Right brace only", "Chỉ nẹp bên phải"]),
  makeCommand("mixed-paren-bracket", "(]", "\\left(\\placeholder{}\\right]", "\\left(x\\right]", "Cặp dấu ngoặc đơn", "Parenthesis-bracket pair", "structure", 66, ["mixed delimiter"], ["Parenthesis-bracket pair", "Cặp dấu ngoặc đơn"]),
  makeCommand("mixed-bracket-paren", "[)", "\\left[\\placeholder{}\\right)", "\\left[x\\right)", "Cặp dấu ngoặc đơn", "Bracket-parenthesis pair", "structure", 66, ["mixed delimiter"], ["Bracket-parenthesis pair", "Cặp dấu ngoặc đơn"]),
  makeCommand("double-brackets", "[[ ]]", "\\left[\\!\\left[\\placeholder{}\\right]\\!\\right]", "\\left[\\!\\left[x\\right]\\!\\right]", "Dấu ngoặc kép", "Double brackets", "structure", 65, ["double brackets"], ["Double brackets", "Dấu ngoặc kép"]),
  makeCommand("moustache-pair", "\\lmoustache", "\\left\\lmoustache\\placeholder{}\\right\\rmoustache", "\\left\\lmoustache x\\right\\rmoustache", "Dấu phân cách ria mép", "Moustache delimiters", "structure", 62, ["moustache"], ["Moustache delimiters", "Dấu phân cách ria mép"]),
  makeCommand("corner-pair", "\\ulcorner", "\\left\\ulcorner\\placeholder{}\\right\\urcorner", "\\left\\ulcorner x\\right\\urcorner", "Dấu phân cách góc trên", "Upper corner delimiters", "structure", 61, ["corner delimiters"], ["Upper corner delimiters", "Dấu phân cách góc trên"]),
  makeCommand("baraccent", "\\bar", "\\bar{\\placeholder{}}", "\\bar{x}", "Giọng thanh", "Bar accent", "structure", 78, ["bar accent"], ["Bar accent", "Giọng thanh"]),
  makeCommand("vecaccent", "\\vec", "\\vec{\\placeholder{}}", "\\vec{x}", "Dấu vector", "Vector accent", "structure", 81, ["vector accent"], ["Vector accent", "Dấu vector"]),
  makeCommand("dddotaccent", "\\dddot", "\\dddot{\\placeholder{}}", "\\dddot{x}", "Dấu ba chấm", "Triple-dot accent", "structure", 68, ["triple dot"], ["Triple-dot accent", "Dấu ba chấm"]),
  makeCommand("ddddotaccent", "\\ddddot", "\\ddddot{\\placeholder{}}", "\\ddddot{x}", "Dấu bốn chấm", "Quadruple-dot accent", "structure", 67, ["quadruple dot"], ["Quadruple-dot accent", "Dấu bốn chấm"]),
  makeCommand("cases-three", "\\begin{cases}", "\\begin{cases}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{cases}", "f(x)=\\begin{cases}a&x<0\\\\b&x=0\\\\c&x>0\\end{cases}", "Thùng ba hàng", "Three-row cases", "structure", 83, ["three cases"], ["Three-row cases", "Thùng ba hàng"]),

  // 微积分与常用函数
  makeCommand("intplain", "\\int", "\\int \\placeholder{}\\,\\mathrm{d}\\placeholder{}", "\\int f(x)\\,\\mathrm{d}x", "Tích phân bất định", "Indefinite integral", "calculus", 99, ["indefinite integral", "integral"], ["Indefinite integral", "Tích phân bất định"]),
  makeCommand("iint-bounds", "\\iint", "\\iint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}A", "\\iint_D^S f\\,\\mathrm{d}A", "Tích phân kép giới hạn", "Bounded double integral", "calculus", 91, ["bounded double integral"], ["Bounded double integral", "Tích phân kép giới hạn"]),
  makeCommand("iiint-bounds", "\\iiint", "\\iiint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V^W f\\,\\mathrm{d}V", "Tích phân bội ba giới hạn", "Bounded triple integral", "calculus", 90, ["bounded triple integral"], ["Bounded triple integral", "Tích phân bội ba giới hạn"]),
  makeCommand("oint-bounds", "\\oint", "\\oint_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}\\placeholder{}", "\\oint_C^D f\\,\\mathrm{d}s", "Tích phân đường viền giới hạn", "Bounded contour integral", "calculus", 89, ["bounded contour integral"], ["Bounded contour integral", "Tích phân đường viền giới hạn"]),
  makeCommand("sum-finite", "\\sum", "\\sum_{\\placeholder{}=\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\sum_{k=1}^{n}a_k", "Tổng hữu hạn", "Finite sum", "calculus", 98, ["finite sum"], ["Finite sum", "Tổng hữu hạn"]),
  makeCommand("prod-finite", "\\prod", "\\prod_{\\placeholder{}=\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\prod_{k=1}^{n}a_k", "Sản phẩm hữu hạn", "Finite product", "calculus", 92, ["finite product"], ["Finite product", "Sản phẩm hữu hạn"]),
  makeCommand("lineintegral", "\\int", "\\int_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}s", "\\int_C f\\,\\mathrm{d}s", "Tích phân đường thẳng", "Line integral", "calculus", 96, ["line integral", "path integral"], ["Line integral", "Tích phân đường thẳng"]),
  makeCommand("surfaceintegral", "\\iint", "\\iint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}S", "\\iint_S f\\,\\mathrm{d}S", "Tích phân bề mặt", "Surface integral", "calculus", 95, ["surface integral", "double integral"], ["Surface integral", "Tích phân bề mặt"]),
  makeCommand("iiint", "\\iiint", "\\iiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V f\\,\\mathrm{d}V", "Tích phân ba", "Triple integral", "calculus", 94, ["triple integral"], ["Triple integral", "Tích phân ba"]),
  makeCommand("volumeintegral", "\\iiint", "\\iiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\iiint_V f\\,\\mathrm{d}V", "Tích phân khối lượng", "Volume integral", "calculus", 93, ["volume integral"], ["Volume integral", "Tích phân khối lượng"]),
  makeCommand("closed-surface-integral", "\\oiint", "\\oiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}S", "\\oiint_S \\mathbf{F}\\cdot\\mathrm{d}\\mathbf{S}", "Tích phân mặt kín", "Closed surface integral", "calculus", 92, ["closed surface integral", "oiint"], ["Closed surface integral", "Tích phân mặt kín"]),
  makeCommand("closed-volume-integral", "\\oiiint", "\\oiiint_{\\placeholder{}} \\placeholder{}\\,\\mathrm{d}V", "\\oiiint_V f\\,\\mathrm{d}V", "Tích phân khối đóng", "Closed volume integral", "calculus", 87, ["closed volume integral", "oiiint"], ["Closed volume integral", "Tích phân khối đóng"]),

  makeCommand("derivative", "\\frac{d}{dx}", "\\frac{\\mathrm{d}\\placeholder{}}{\\mathrm{d}\\placeholder{}}", "\\frac{\\mathrm{d}f}{\\mathrm{d}x}", "Đạo hàm", "Derivative", "calculus", 91, ["derivative"], ["Derivative", "Đạo hàm"]),
  makeCommand("secondderivative", "\\frac{d^2}{dx^2}", "\\frac{\\mathrm{d}^{2}\\placeholder{}}{\\mathrm{d}\\placeholder{}^{2}}", "\\frac{\\mathrm{d}^{2}f}{\\mathrm{d}x^{2}}", "Đạo hàm bậc hai", "Second derivative", "calculus", 83, ["second derivative"], ["Second derivative", "Đạo hàm bậc hai"]),
  makeCommand("partialsecond", "\\partial^2", "\\frac{\\partial^{2}\\placeholder{}}{\\partial\\placeholder{}^{2}}", "\\frac{\\partial^{2}f}{\\partial x^{2}}", "Phần thứ hai", "Second partial", "calculus", 82, ["second partial"], ["Second partial", "Phần thứ hai"]),
  makeCommand("mixedpartial", "\\partial^2", "\\frac{\\partial^{2}\\placeholder{}}{\\partial\\placeholder{}\\partial\\placeholder{}}", "\\frac{\\partial^{2}f}{\\partial x\\partial y}", "Hỗn hợp một phần", "Mixed partial", "calculus", 81, ["mixed partial"], ["Mixed partial", "Hỗn hợp một phần"]),
  makeCommand("evalbar", "\\left.", "\\left.\\placeholder{}\\right|_{\\placeholder{}}^{\\placeholder{}}", "\\left.F(x)\\right|_a^b", "Đánh giá", "Evaluation", "calculus", 80, ["evaluate"], ["Evaluation", "Đánh giá"]),
  makeCommand("series", "\\sum", "\\sum_{\\placeholder{}=0}^{\\infty} \\placeholder{}", "\\sum_{n=0}^{\\infty}a_n", "Chuỗi vô hạn", "Infinite series", "calculus", 97, ["series", "summation"], ["Infinite series", "Chuỗi vô hạn"]),
  makeCommand("productseries", "\\prod", "\\prod_{\\placeholder{}=1}^{\\infty} \\placeholder{}", "\\prod_{n=1}^{\\infty}a_n", "Sản phẩm vô tận", "Infinite product", "calculus", 94, ["infinite product", "product"], ["Infinite product", "Sản phẩm vô tận"]),
  makeCommand("coproduct", "\\coprod", "\\coprod_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\coprod_{i=1}^{n} A_i", "Bản sao", "Coproduct", "calculus", 84, ["coproduct"], ["Coproduct", "Bản sao"]),
  makeCommand("bigcap-limits", "\\bigcap", "\\bigcap_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigcap_{i=1}^{n}A_i", "Ngã tư lớn", "Big intersection", "calculus", 88, ["big intersection"], ["Big intersection", "Ngã tư lớn"]),
  makeCommand("bigcup-limits", "\\bigcup", "\\bigcup_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigcup_{i=1}^{n}A_i", "Công đoàn lớn", "Big union", "calculus", 88, ["big union"], ["Big union", "Công đoàn lớn"]),
  makeCommand("bigsqcup-limits", "\\bigsqcup", "\\bigsqcup_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigsqcup_{i=1}^{n}A_i", "Hợp vuông lớn", "Big square union", "calculus", 82, ["big square union"], ["Big square union", "Hợp vuông lớn"]),
  makeCommand("bigvee-limits", "\\bigvee", "\\bigvee_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigvee_{i=1}^{n}P_i", "Logic lớn hay", "Big logical or", "calculus", 84, ["big vee"], ["Big logical or", "Logic lớn hay"]),
  makeCommand("bigwedge-limits", "\\bigwedge", "\\bigwedge_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigwedge_{i=1}^{n}P_i", "Hợp lý và lớn lao", "Big logical and", "calculus", 84, ["big wedge"], ["Big logical and", "Hợp lý và lớn lao"]),
  makeCommand("bigodot-limits", "\\bigodot", "\\bigodot_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigodot_{i=1}^{n}A_i", "Chấm tròn to", "Big circled dot", "calculus", 80, ["big odot"], ["Big circled dot", "Chấm tròn to"]),
  makeCommand("bigoplus-limits", "\\bigoplus", "\\bigoplus_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigoplus_{i=1}^{n}V_i", "Số tiền trực tiếp lớn", "Big direct sum", "calculus", 86, ["big direct sum"], ["Big direct sum", "Số tiền trực tiếp lớn"]),
  makeCommand("bigotimes-limits", "\\bigotimes", "\\bigotimes_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\bigotimes_{i=1}^{n}V_i", "Sản phẩm tensor lớn", "Big tensor product", "calculus", 86, ["big tensor product"], ["Big tensor product", "Sản phẩm tensor lớn"]),
  makeCommand("biguplus-limits", "\\biguplus", "\\biguplus_{\\placeholder{}}^{\\placeholder{}} \\placeholder{}", "\\biguplus_{i=1}^{n}A_i", "Liên minh nhiều bộ lớn", "Big multiset union", "calculus", 80, ["big uplus"], ["Big multiset union", "Liên minh nhiều bộ lớn"]),
  makeCommand("lim-infty", "\\lim", "\\lim_{\\placeholder{}\\to\\infty} \\placeholder{}", "\\lim_{x\\to\\infty}f(x)", "Giới hạn ở vô cực", "Limit at infinity", "calculus", 95, ["limit infinity"], ["Limit at infinity", "Giới hạn ở vô cực"]),
  makeCommand("lim-left", "\\lim", "\\lim_{\\placeholder{}\\to\\placeholder{}^{-}} \\placeholder{}", "\\lim_{x\\to a^-}f(x)", "Giới hạn bên trái", "Left-hand limit", "calculus", 93, ["left limit"], ["Left-hand limit", "Giới hạn bên trái"]),
  makeCommand("lim-right", "\\lim", "\\lim_{\\placeholder{}\\to\\placeholder{}^{+}} \\placeholder{}", "\\lim_{x\\to a^+}f(x)", "Giới hạn bên phải", "Right-hand limit", "calculus", 93, ["right limit"], ["Right-hand limit", "Giới hạn bên phải"]),
  makeCommand("log", "\\log", "\\log_{\\placeholder{}}\\left(\\placeholder{}\\right)", "\\log_a x", "Lôgarit", "Logarithm", "calculus", 86, ["logarithm"], ["Logarithm", "Lôgarit"]),
  makeCommand("ln", "\\ln", "\\ln\\left(\\placeholder{}\\right)", "\\ln x", "Gỗ tự nhiên", "Natural log", "calculus", 87, ["natural log"], ["Natural log", "Gỗ tự nhiên"]),
  makeCommand("exp", "\\exp", "\\exp\\left(\\placeholder{}\\right)", "\\exp(x)", "Hàm mũ", "Exponential", "calculus", 85, ["exponential"], ["Exponential", "Hàm mũ"]),
  makeCommand("sin", "\\sin", "\\sin\\left(\\placeholder{}\\right)", "\\sin x", "Sin", "Sine", "calculus", 89, ["sine"], ["Sine", "Sin"]),
  makeCommand("cos", "\\cos", "\\cos\\left(\\placeholder{}\\right)", "\\cos x", "cosin", "Cosine", "calculus", 89, ["cosine"], ["Cosine", "cosin"]),
  makeCommand("tan", "\\tan", "\\tan\\left(\\placeholder{}\\right)", "\\tan x", "Tiếp tuyến", "Tangent", "calculus", 84, ["tangent"], ["Tangent", "Tiếp tuyến"]),
  makeCommand("arcsin", "\\arcsin", "\\arcsin\\left(\\placeholder{}\\right)", "\\arcsin x", "Arcsin", "Arcsine", "calculus", 74, ["arcsine"], ["Arcsine", "Arcsin"]),
  makeCommand("min", "\\min", "\\min_{\\placeholder{}}\\placeholder{}", "\\min_x f(x)", "Tối thiểu", "Minimum", "calculus", 78, ["minimum"], ["Minimum", "Tối thiểu"]),
  makeCommand("max", "\\max", "\\max_{\\placeholder{}}\\placeholder{}", "\\max_x f(x)", "Tối đa", "Maximum", "calculus", 78, ["maximum"], ["Maximum", "Tối đa"]),

  // 矩阵与线性代数
  makeCommand("matrixplain2", "\\begin{matrix}", "\\begin{matrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{matrix}", "\\begin{matrix}a&b\\\\c&d\\end{matrix}", "Ma trận trơn", "Plain matrix", "matrix", 82, ["matrix"], ["Plain matrix", "Ma trận trơn"]),
  makeCommand("Bmatrix2", "\\begin{Bmatrix}", "\\begin{Bmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{Bmatrix}", "\\begin{Bmatrix}a&b\\\\c&d\\end{Bmatrix}", "Ma trận nẹp", "Brace matrix", "matrix", 80, ["Bmatrix"], ["Brace matrix", "Ma trận nẹp"]),
  makeCommand("Vmatrix2", "\\begin{Vmatrix}", "\\begin{Vmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{Vmatrix}", "\\begin{Vmatrix}a&b\\\\c&d\\end{Vmatrix}", "Ma trận thanh đôi", "Double-bar matrix", "matrix", 78, ["Vmatrix"], ["Double-bar matrix", "Ma trận thanh đôi"]),
  makeCommand("rowvector", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} & \\placeholder{} & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a&b&c\\end{bmatrix}", "Vectơ hàng", "Row vector", "matrix", 86, ["row vector"], ["Row vector", "Vectơ hàng"]),
  makeCommand("colvector", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} \\\\ \\placeholder{} \\\\ \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a\\\\b\\\\c\\end{bmatrix}", "Vectơ cột", "Column vector", "matrix", 86, ["column vector"], ["Column vector", "Vectơ cột"]),
  makeCommand("det", "\\det", "\\det\\left(\\placeholder{}\\right)", "\\det(A)", "Toán tử xác định", "Determinant operator", "matrix", 82, ["det"], ["Determinant operator", "Toán tử xác định"]),
  makeCommand("trace", "\\operatorname{tr}", "\\operatorname{tr}\\left(\\placeholder{}\\right)", "\\operatorname{tr}(A)", "Dấu vết", "Trace", "matrix", 78, ["trace", "tr"], ["Trace", "Dấu vết"]),
  makeCommand("rank", "\\operatorname{rank}", "\\operatorname{rank}\\left(\\placeholder{}\\right)", "\\operatorname{rank}(A)", "Thứ hạng", "Rank", "matrix", 78, ["rank"], ["Rank", "Thứ hạng"]),
  makeCommand("norm", "\\lVert", "\\left\\lVert\\placeholder{}\\right\\rVert", "\\lVert\\mathbf{x}\\rVert", "Định mức", "Norm", "matrix", 81, ["norm"], ["Norm", "Định mức"]),
  makeCommand("unitvector", "\\hat", "\\hat{\\mathbf{\\placeholder{}}}", "\\hat{\\mathbf{e}}", "Vectơ đơn vị", "Unit vector", "matrix", 84, ["unit vector"], ["Unit vector", "Vectơ đơn vị"]),
  makeCommand("matrix-dots", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} & \\cdots & \\placeholder{} \\\\ \\vdots & \\ddots & \\vdots \\\\ \\placeholder{} & \\cdots & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a_{11}&\\cdots&a_{1n}\\\\\\vdots&\\ddots&\\vdots\\\\a_{m1}&\\cdots&a_{mn}\\end{bmatrix}", "Ma trận dấu ba chấm", "Ellipsis matrix", "matrix", 90, ["ellipsis matrix"], ["Ellipsis matrix", "Ma trận dấu ba chấm"]),
  makeCommand("diagonal-matrix", "\\operatorname{diag}", "\\begin{bmatrix}\\placeholder{} & 0 & \\cdots & 0 \\\\ 0 & \\placeholder{} & \\ddots & \\vdots \\\\ \\vdots & \\ddots & \\ddots & 0 \\\\ 0 & \\cdots & 0 & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}a_1&0&\\cdots&0\\\\0&a_2&\\ddots&\\vdots\\\\\\vdots&\\ddots&\\ddots&0\\\\0&\\cdots&0&a_n\\end{bmatrix}", "Ma trận đường chéo", "Diagonal matrix", "matrix", 88, ["diagonal matrix"], ["Diagonal matrix", "Ma trận đường chéo"]),
  makeCommand("augmented-matrix", "\\left[", "\\left[\\begin{array}{cc|c}\\placeholder{} & \\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{} & \\placeholder{}\\end{array}\\right]", "\\left[\\begin{array}{cc|c}1&0&a\\\\0&1&b\\end{array}\\right]", "Ma trận mở rộng", "Augmented matrix", "matrix", 87, ["augmented matrix"], ["Augmented matrix", "Ma trận mở rộng"]),
  makeCommand("block-matrix", "\\begin{bmatrix}", "\\begin{bmatrix}\\placeholder{} & \\placeholder{} \\\\ \\placeholder{} & \\placeholder{}\\end{bmatrix}", "\\begin{bmatrix}A&B\\\\C&D\\end{bmatrix}", "Ma trận khối", "Block matrix", "matrix", 85, ["block matrix"], ["Block matrix", "Ma trận khối"]),

  // 物理常用结构
  makeCommand("expectation", "\\langle", "\\left\\langle\\placeholder{}\\right\\rangle", "\\langle A\\rangle", "Giá trị kỳ vọng", "Expectation value", "physics", 90, ["expectation"], ["Expectation value", "Giá trị kỳ vọng"]),
  makeCommand("braket", "\\langle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\phi|\\psi\\rangle", "Giá đỡ", "Bra-ket", "physics", 92, ["braket", "inner product"], ["Bra-ket", "Giá đỡ"]),
  makeCommand("commutator", "[", "\\left[\\placeholder{},\\placeholder{}\\right]", "[A,B]", "Cổ góp", "Commutator", "physics", 88, ["commutator"], ["Commutator", "Cổ góp"]),
  makeCommand("anticommutator", "\\{", "\\left\\{\\placeholder{},\\placeholder{}\\right\\}", "\\{A,B\\}", "Bộ phản chuyển mạch", "Anticommutator", "physics", 82, ["anticommutator"], ["Anticommutator", "Bộ phản chuyển mạch"]),
  makeCommand("timederivative", "\\dot", "\\dot{\\placeholder{}}", "\\dot{x}", "Đạo hàm thời gian", "Time derivative", "physics", 86, ["dot derivative"], ["Time derivative", "Đạo hàm thời gian"]),
  makeCommand("timesecond", "\\ddot", "\\ddot{\\placeholder{}}", "\\ddot{x}", "Đạo hàm lần thứ hai", "Second time derivative", "physics", 84, ["double dot"], ["Second time derivative", "Đạo hàm lần thứ hai"]),
  makeCommand("outerproduct", "|\\psi\\rangle\\langle\\phi|", "|\\placeholder{}\\rangle\\langle\\placeholder{}|", "|\\psi\\rangle\\langle\\phi|", "Sản phẩm bên ngoài", "Outer product", "physics", 91, ["outer product", "ket bra"], ["Outer product", "Sản phẩm bên ngoài"]),
  makeCommand("matrixelement", "\\langle\\phi|\\hat A|\\psi\\rangle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\phi|\\hat A|\\psi\\rangle", "Phần tử ma trận", "Matrix element", "physics", 90, ["matrix element"], ["Matrix element", "Phần tử ma trận"]),
  makeCommand("expectation-operator", "\\langle\\psi|\\hat A|\\psi\\rangle", "\\left\\langle\\placeholder{}\\middle|\\placeholder{}\\middle|\\placeholder{}\\right\\rangle", "\\langle\\psi|\\hat A|\\psi\\rangle", "Kỳ vọng của nhà điều hành", "Operator expectation", "physics", 89, ["operator expectation"], ["Operator expectation", "Kỳ vọng của nhà điều hành"]),

  makeCommand("time-ordering", "\\mathcal{T}", "\\mathcal{T}\\left\\{\\placeholder{}\\right\\}", "\\mathcal{T}\\{A(t)B(t')\\}", "Thứ tự thời gian", "Time ordering", "physics", 75, ["time ordering"], ["Time ordering", "Thứ tự thời gian"]),
];

type SimpleDefinition = [
  id: string,
  command: string,
  labelVi: string,
  labelEn: string,
  category: CommandCategory,
  priority?: number,
  aliases?: string[],
  keywords?: string[],
];

const simpleDefinitions: SimpleDefinition[] = [
  // 矩阵
  ["transpose", "^{\\mathsf{T}}", "Chuyển cung", "Transpose", "matrix", 84, ["transpose"], ["Transpose", "Chuyển cung"]],
  ["inverse", "^{-1}", "Nghịch đảo", "Inverse", "matrix", 85, ["inverse"], ["Inverse", "Nghịch đảo"]],
  ["dotproduct", "\\cdot", "Sản phẩm chấm", "Dot product", "matrix", 83, ["dot product"], ["Dot product", "Sản phẩm chấm"]],
  ["crossproduct", "\\times", "Sản phẩm chéo", "Cross product", "matrix", 83, ["cross product"], ["Cross product", "Sản phẩm chéo"]],

  // 二元运算符
  ["plusminus", "\\pm", "Cộng-trừ", "Plus-minus", "relation", 94],
  ["minusplus", "\\mp", "Trừ-cộng", "Minus-plus", "relation", 86],
  ["multiply", "\\times", "Phép nhân", "Multiplication", "relation", 94],
  ["division", "\\div", "Phòng", "Division", "relation", 92],
  ["centerdot", "\\cdot", "Dấu chấm ở giữa", "Centered dot", "relation", 90],
  ["asterisk", "\\ast", "Toán tử dấu hoa thị", "Asterisk operator", "relation", 76],
  ["starop", "\\star", "Toán tử ngôi sao", "Star operator", "relation", 74],
  ["circleop", "\\circ", "Toán tử vòng tròn", "Circle operator", "relation", 78],
  ["bulletop", "\\bullet", "Người điều khiển viên đạn", "Bullet operator", "relation", 78],
  ["diamondop", "\\diamond", "Toán tử kim cương", "Diamond operator", "relation", 72],
  ["triangleop", "\\triangle", "Toán tử tam giác", "Triangle operator", "relation", 70],
  ["triangledownop", "\\triangledown", "Toán tử tam giác xuống", "Down triangle operator", "relation", 70],
  ["bigtriangleupop", "\\bigtriangleup", "Tam giác lớn lên", "Big triangle up", "relation", 68],
  ["bigtriangledownop", "\\bigtriangledown", "Tam giác lớn hướng xuống", "Big triangle down", "relation", 68],
  ["ominus", "\\ominus", "Khoanh tròn dấu trừ", "Circled minus", "relation", 82],
  ["oslash", "\\oslash", "Dấu gạch chéo tròn", "Circled slash", "relation", 78],
  ["odot", "\\odot", "Dấu chấm tròn", "Circled dot", "relation", 82],
  ["circledast", "\\circledast", "Dấu hoa thị khoanh tròn", "Circled asterisk", "relation", 74],
  ["circledcirc", "\\circledcirc", "Vòng tròn tròn", "Circled circle", "relation", 72],
  ["circleddash", "\\circleddash", "Dấu gạch ngang được khoanh tròn", "Circled dash", "relation", 72],
  ["boxplus", "\\boxplus", "Kèm hộp", "Boxed plus", "relation", 76],
  ["boxminus", "\\boxminus", "Đóng hộp trừ", "Boxed minus", "relation", 74],
  ["boxtimes", "\\boxtimes", "Thời gian đóng hộp", "Boxed times", "relation", 76],
  ["boxdot", "\\boxdot", "Dấu chấm đóng hộp", "Boxed dot", "relation", 74],
  ["uplus", "\\uplus", "Liên kết nhiều bộ", "Multiset union", "relation", 76],
  ["sqcap", "\\sqcap", "Ngã tư vuông", "Square intersection", "relation", 74],
  ["sqcup", "\\sqcup", "Liên vuông", "Square union", "relation", 74],
  ["amalg", "\\amalg", "Hợp nhất", "Amalgamation", "relation", 66],
  ["wreath", "\\wr", "Sản phẩm vòng hoa", "Wreath product", "relation", 64],
  ["divideontimes", "\\divideontimes", "Chia thời gian", "Divide on times", "relation", 64],
  ["ltimes", "\\ltimes", "Tích bán trực tiếp bên trái", "Left semidirect product", "relation", 68],
  ["rtimes", "\\rtimes", "Sản phẩm bán trực tiếp bên phải", "Right semidirect product", "relation", 68],
  ["leftthreetimes", "\\leftthreetimes", "Sang trái ba lần", "Left three-times", "relation", 64],
  ["rightthreetimes", "\\rightthreetimes", "Đúng ba lần", "Right three-times", "relation", 64],
  ["intercal", "\\intercal", "Intercal", "Intercal", "relation", 62],

  // 希腊字母
  ["epsilon", "\\epsilon", "Epsilon", "Epsilon", "greek", 82],
  ["varepsilon", "\\varepsilon", "Biến thể epsilon", "Variant epsilon", "greek", 80],
  ["zeta", "\\zeta", "Zeta", "Zeta", "greek", 78],
  ["eta", "\\eta", "Eta", "Eta", "greek", 78],
  ["vartheta", "\\vartheta", "Biến thể theta", "Variant theta", "greek", 78],
  ["iota", "\\iota", "Iota", "Iota", "greek", 76],
  ["kappa", "\\kappa", "Kappa", "Kappa", "greek", 80],
  ["nu", "\\nu", "Nữ", "Nu", "greek", 79],
  ["xi", "\\xi", "Xi", "Xi", "greek", 76],
  ["rho", "\\rho", "Rho", "Rho", "greek", 82],
  ["varrho", "\\varrho", "Biến thể rho", "Variant rho", "greek", 72],
  ["tau", "\\tau", "Tàu", "Tau", "greek", 81],
  ["upsilon", "\\upsilon", "Upsilon", "Upsilon", "greek", 70],
  ["phi", "\\phi", "Phi", "Phi", "greek", 86],
  ["varphi", "\\varphi", "Biến thể phi", "Variant phi", "greek", 84],
  ["chi", "\\chi", "Chí", "Chi", "greek", 74],
  ["psi", "\\psi", "Psi", "Psi", "greek", 84],
  ["Gamma", "\\Gamma", "Gamma", "Gamma", "greek", 76],
  ["Delta", "\\Delta", "Đồng bằng", "Delta", "greek", 84],
  ["Theta", "\\Theta", "Theta", "Theta", "greek", 72],
  ["Lambda", "\\Lambda", "Lambda", "Lambda", "greek", 76],
  ["Xi", "\\Xi", "Xi", "Xi", "greek", 68],
  ["Pi", "\\Pi", "Pi", "Pi", "greek", 74],
  ["Sigma", "\\Sigma", "Sigma", "Sigma", "greek", 78],
  ["Phi", "\\Phi", "Phi", "Phi", "greek", 76],
  ["Psi", "\\Psi", "Psi", "Psi", "greek", 78],
  ["Omega", "\\Omega", "Omega", "Omega", "greek", 82],
  ["varpi", "\\varpi", "Biến thể pi", "Variant pi", "greek", 73],
  ["varsigma", "\\varsigma", "Sigma cuối cùng", "Final sigma", "greek", 71],
  ["digamma", "\\digamma", "Hình ảnh mờ", "Digamma", "greek", 68],

  // 关系符号
  ["lt", "<", "Nhỏ hơn", "Less than", "relation", 92],
  ["gt", ">", "Lớn hơn", "Greater than", "relation", 92],
  ["equiv", "\\equiv", "Tương đương", "Equivalent", "relation", 88],
  ["sim", "\\sim", "Tương tự", "Similar", "relation", 82],
  ["simeq", "\\simeq", "tiệm cận bằng nhau", "Asymptotically equal", "relation", 80],
  ["cong", "\\cong", "Đồng đẳng", "Congruent", "relation", 78],
  ["ll", "\\ll", "Ít hơn nhiều", "Much less", "relation", 82],
  ["gg", "\\gg", "Tuyệt vời hơn nhiều", "Much greater", "relation", 82],
  ["parallel", "\\parallel", "Song song", "Parallel", "relation", 79],
  ["perp", "\\perp", "Vuông góc", "Perpendicular", "relation", 81],
  ["mid", "\\mid", "Chia", "Divides", "relation", 74],
  ["nmid", "\\nmid", "Không chia", "Does not divide", "relation", 72],
  ["prec", "\\prec", "Trước", "Precedes", "relation", 68],
  ["succ", "\\succ", "Thành công", "Succeeds", "relation", 68],
  ["leqq", "\\leqq", "Nhỏ hơn hoặc bằng (gấp đôi)", "Less than or equal (double)", "relation", 77],
  ["geqq", "\\geqq", "Lớn hơn hoặc bằng (gấp đôi)", "Greater than or equal (double)", "relation", 77],
  ["lneq", "\\lneq", "Nhỏ hơn nhưng không bằng", "Less than but not equal", "relation", 75],
  ["gneq", "\\gneq", "Lớn hơn nhưng không bằng", "Greater than but not equal", "relation", 75],
  ["lesssim", "\\lesssim", "Nhỏ hơn hoặc tương tự", "Less than or similar", "relation", 74],
  ["gtrsim", "\\gtrsim", "Lớn hơn hoặc tương đương", "Greater than or similar", "relation", 74],
  ["lessapprox", "\\lessapprox", "Nhỏ hơn hoặc xấp xỉ bằng", "Less than or approximately equal", "relation", 73],
  ["gtrapprox", "\\gtrapprox", "Lớn hơn hoặc xấp xỉ bằng", "Greater than or approximately equal", "relation", 73],
  ["preceq", "\\preceq", "Đi trước hoặc bằng", "Precedes or equals", "relation", 72],
  ["succeq", "\\succeq", "Thành công hoặc bằng", "Succeeds or equals", "relation", 72],
  ["asymp", "\\asymp", "Tương đương tiệm cận", "Asymptotically equivalent", "relation", 76],
  ["doteq", "\\doteq", "Dấu chấm bằng", "Dotted equals", "relation", 71],
  ["triangleq", "\\triangleq", "Được định nghĩa là", "Defined as", "relation", 78],
  ["models", "\\models", "Model", "Models", "relation", 74],
  ["vdash", "\\vdash", "Chứng minh", "Proves", "relation", 73],
  ["dashv", "\\dashv", "Cửa quay ngược", "Reverse turnstile", "relation", 67],
  ["bowtie", "\\bowtie", "Quan hệ thắt nơ", "Bowtie relation", "relation", 66],
  ["smile", "\\smile", "Nụ cười quan hệ", "Smile relation", "relation", 64],
  ["frown", "\\frown", "Quan hệ cau mày", "Frown relation", "relation", 64],
  ["approxeq", "\\approxeq", "Gần bằng nhau", "Approximately equal", "relation", 78],
  ["eqsim", "\\eqsim", "Tương đương hoặc tương tự", "Equal or similar", "relation", 72],
  ["backsim", "\\backsim", "Đảo ngược tương tự", "Reverse similar", "relation", 68],
  ["backsimeq", "\\backsimeq", "Đảo tiệm cận bằng nhau", "Reverse asymptotically equal", "relation", 67],
  ["fallingdotseq", "\\fallingdotseq", "Rơi chấm bằng", "Falling dotted equals", "relation", 66],
  ["risingdotseq", "\\risingdotseq", "Dấu chấm tăng lên bằng", "Rising dotted equals", "relation", 66],
  ["eqcirc", "\\eqcirc", "Vòng tròn bằng nhau", "Equal circle", "relation", 68],
  ["circeq", "\\circeq", "Vòng tròn bằng nhau", "Circle equal", "relation", 68],
  ["bumpeq", "\\bumpeq", "Cú va chạm bằng", "Bump equals", "relation", 66],
  ["Bumpeq", "\\Bumpeq", "Cú va chạm kép bằng", "Double bump equals", "relation", 66],
  ["between", "\\between", "Giữa", "Between", "relation", 64],
  ["pitchfork", "\\pitchfork", "Cây chĩa", "Pitchfork", "relation", 64],
  ["therefore", "\\therefore", "Vì vậy", "Therefore", "relation", 76],
  ["because", "\\because", "Bởi vì", "Because", "relation", 76],
  ["plus", "+", "Plus", "Plus", "relation", 100],
  ["minus", "-", "Trừ", "Minus", "relation", 100],
  ["colonop", ":", "Đại tràng", "Colon", "relation", 78],
  ["ldots", "\\ldots", "Chấm thấp", "Low dots", "relation", 74],
  ["cdots", "\\cdots", "Dấu chấm ở giữa", "Centered dots", "relation", 76],
  ["vdots", "\\vdots", "Chấm dọc", "Vertical dots", "relation", 74],
  ["ddots", "\\ddots", "Chấm chéo", "Diagonal dots", "relation", 74],
  ["nless", "\\nless", "Không nhỏ hơn", "Not less than", "relation", 72],
  ["ngtr", "\\ngtr", "Không lớn hơn", "Not greater than", "relation", 72],
  ["nleq", "\\nleq", "Không nhỏ hơn hoặc bằng", "Not less or equal", "relation", 72],
  ["ngeq", "\\ngeq", "Không lớn hơn hoặc bằng", "Not greater or equal", "relation", 72],
  ["leqslant", "\\leqslant", "Nghiêng ít hoặc bằng", "Slanted less or equal", "relation", 76],
  ["geqslant", "\\geqslant", "Nghiêng lớn hơn hoặc bằng", "Slanted greater or equal", "relation", 76],
  ["lessdot", "\\lessdot", "Ít hơn bằng dấu chấm", "Less with dot", "relation", 66],
  ["gtrdot", "\\gtrdot", "Lớn hơn có dấu chấm", "Greater with dot", "relation", 66],
  ["lessgtr", "\\lessgtr", "Nhỏ hơn hoặc lớn hơn", "Less or greater", "relation", 68],
  ["gtrless", "\\gtrless", "Lớn hơn hoặc nhỏ hơn", "Greater or less", "relation", 68],
  ["lesseqgtr", "\\lesseqgtr", "Nhỏ hơn hoặc lớn hơn", "Less-equal or greater", "relation", 66],
  ["gtreqless", "\\gtreqless", "Lớn hơn hoặc nhỏ hơn", "Greater-equal or less", "relation", 66],
  ["triangleleft", "\\triangleleft", "Tam giác trái", "Triangle left", "relation", 72],
  ["triangleright", "\\triangleright", "Tam giác vuông", "Triangle right", "relation", 72],
  ["trianglelefteq", "\\trianglelefteq", "Tam giác trái hoặc bằng", "Triangle left or equal", "relation", 70],
  ["trianglerighteq", "\\trianglerighteq", "Tam giác vuông hoặc bằng", "Triangle right or equal", "relation", 70],
  ["vartriangleleft", "\\vartriangleleft", "Biến thể tam giác bên trái", "Variant triangle left", "relation", 68],
  ["vartriangleright", "\\vartriangleright", "Biến thể tam giác vuông", "Variant triangle right", "relation", 68],
  ["ntriangleleft", "\\ntriangleleft", "Không trái tam giác", "Not triangle left", "relation", 64],
  ["ntriangleright", "\\ntriangleright", "Không phải tam giác vuông", "Not triangle right", "relation", 64],
  ["ntrianglelefteq", "\\ntrianglelefteq", "Không phải tam giác trái hoặc bằng", "Not triangle left or equal", "relation", 62],
  ["ntrianglerighteq", "\\ntrianglerighteq", "Không phải tam giác vuông hoặc bằng", "Not triangle right or equal", "relation", 62],
  ["square-symbol", "\\square", "Vuông", "Square", "relation", 70],
  ["blacksquare-symbol", "\\blacksquare", "Hình vuông màu đen", "Black square", "relation", 68],
  ["lozenge-symbol", "\\lozenge", "Viên ngậm", "Lozenge", "relation", 70],
  ["blacklozenge-symbol", "\\blacklozenge", "Viên ngậm đen", "Black lozenge", "relation", 68],
  ["bigcirc-symbol", "\\bigcirc", "Vòng tròn lớn", "Big circle", "relation", 70],
  ["blacktriangle-symbol", "\\blacktriangle", "Tam giác đen", "Black triangle", "relation", 66],
  ["blacktriangledown-symbol", "\\blacktriangledown", "Tam giác đen hướng xuống", "Black triangle down", "relation", 66],
  ["blacktriangleleft-symbol", "\\blacktriangleleft", "Tam giác đen bên trái", "Black triangle left", "relation", 66],
  ["blacktriangleright-symbol", "\\blacktriangleright", "Tam giác đen bên phải", "Black triangle right", "relation", 66],

  // 集合与逻辑
  ["subseteq", "\\subseteq", "Tập con hoặc bằng", "Subset or equal", "set", 88],
  ["supset", "\\supset", "Siêu bộ", "Superset", "set", 86],
  ["supseteq", "\\supseteq", "Superset hoặc bằng", "Superset or equal", "set", 84],
  ["sqsubset", "\\sqsubset", "Tập con hình vuông", "Square subset", "set", 76],
  ["sqsupset", "\\sqsupset", "Bộ siêu hình vuông", "Square superset", "set", 76],
  ["sqsubseteq", "\\sqsubseteq", "Tập con vuông hoặc bằng", "Square subset or equal", "set", 78],
  ["sqsupseteq", "\\sqsupseteq", "Bộ siêu vuông hoặc bằng", "Square superset or equal", "set", 78],
  ["Subset", "\\Subset", "Tập con đôi", "Double subset", "set", 72],
  ["Supset", "\\Supset", "Bộ siêu đôi", "Double superset", "set", 72],
  ["subseteqq", "\\subseteqq", "Tập con đôi hoặc bằng nhau", "Double subset or equal", "set", 74],
  ["supseteqq", "\\supseteqq", "Bộ đôi hoặc bằng", "Double superset or equal", "set", 74],
  ["nsubseteq", "\\nsubseteq", "Không phải tập con hoặc bằng", "Not subset or equal", "set", 70],
  ["nsupseteq", "\\nsupseteq", "Không siêu hoặc bằng", "Not superset or equal", "set", 70],
  ["ni", "\\ni", "Chứa với tư cách là thành viên", "Contains as member", "set", 90],
  ["notni", "\\not\\ni", "Không chứa tư cách thành viên", "Does not contain as member", "set", 74],
  ["smallsetminus", "\\smallsetminus", "Chênh lệch tập hợp nhỏ", "Small set difference", "set", 76],
  ["emptyset", "\\emptyset", "Bộ trống", "Empty set", "set", 90],
  ["setminus", "\\setminus", "Đặt chênh lệch", "Set difference", "set", 82],
  ["land", "\\land", "Hợp lý và", "Logical and", "set", 86],
  ["lor", "\\lor", "Hợp lý hoặc", "Logical or", "set", 86],
  ["neg", "\\neg", "Không logic", "Logical not", "set", 84],
  ["Nset", "\\mathbb{N}", "Số tự nhiên", "Natural numbers", "set", 88],
  ["Zset", "\\mathbb{Z}", "Số nguyên", "Integers", "set", 88],
  ["Qset", "\\mathbb{Q}", "Lý lẽ", "Rationals", "set", 86],
  ["Rset", "\\mathbb{R}", "Số thực", "Real numbers", "set", 92],
  ["Cset", "\\mathbb{C}", "Số phức", "Complex numbers", "set", 90],

  // 箭头
  ["uparrow", "\\uparrow", "Mũi tên lên", "Up arrow", "arrow", 84],
  ["downarrow", "\\downarrow", "Mũi tên xuống", "Down arrow", "arrow", 84],
  ["updownarrow", "\\updownarrow", "Mũi tên lên xuống", "Up-down arrow", "arrow", 76],
  ["Leftarrow", "\\Leftarrow", "Mũi tên kép trái", "Left double arrow", "arrow", 82],
  ["Leftrightarrow", "\\Leftrightarrow", "Nếu và chỉ nếu", "If and only if", "arrow", 88],
  ["mapsto", "\\mapsto", "Bản đồ tới", "Maps to", "arrow", 86],
  ["longrightarrow", "\\longrightarrow", "Mũi tên dài phải", "Long right arrow", "arrow", 78],
  ["longleftarrow", "\\longleftarrow", "Mũi tên trái dài", "Long left arrow", "arrow", 76],
  ["hookrightarrow", "\\hookrightarrow", "Mũi tên móc phải", "Right hook arrow", "arrow", 72],
  ["rightharpoonup", "\\rightharpoonup", "Cây lao phải", "Right harpoon", "arrow", 70],
  ["leftharpoonup", "\\leftharpoonup", "Cây lao trái", "Left harpoon", "arrow", 70],
  ["rightleftarrows", "\\rightleftarrows", "Mũi tên cân bằng", "Equilibrium arrows", "arrow", 78],
  ["longleftrightarrow", "\\longleftrightarrow", "Mũi tên dài trái phải", "Long left-right arrow", "arrow", 78],
  ["Longrightarrow", "\\Longrightarrow", "Mũi tên kép dài bên phải", "Long right double arrow", "arrow", 82],
  ["Longleftarrow", "\\Longleftarrow", "Mũi tên kép dài bên trái", "Long left double arrow", "arrow", 80],
  ["Longleftrightarrow", "\\Longleftrightarrow", "Mũi tên tương đương dài", "Long equivalence arrow", "arrow", 84],
  ["longmapsto", "\\longmapsto", "Mũi tên bản đồ dài tới", "Long maps-to arrow", "arrow", 76],
  ["hookleftarrow", "\\hookleftarrow", "Mũi tên móc trái", "Left hook arrow", "arrow", 72],
  ["rightharpoondown", "\\rightharpoondown", "Lao lao xuống bên phải", "Right harpoon down", "arrow", 69],
  ["leftharpoondown", "\\leftharpoondown", "Cây lao bên trái hạ xuống", "Left harpoon down", "arrow", 69],
  ["rightleftharpoons", "\\rightleftharpoons", "Lao móc phải trái", "Right-left harpoons", "arrow", 79],
  ["leftrightharpoons", "\\leftrightharpoons", "Lao móc trái phải", "Left-right harpoons", "arrow", 77],
  ["nearrow", "\\nearrow", "Mũi tên hướng Đông Bắc", "North-east arrow", "arrow", 68],
  ["nwarrow", "\\nwarrow", "Mũi tên hướng Tây Bắc", "North-west arrow", "arrow", 68],
  ["searrow", "\\searrow", "Mũi tên hướng Đông Nam", "South-east arrow", "arrow", 68],
  ["swarrow", "\\swarrow", "Mũi tên hướng Tây Nam", "South-west arrow", "arrow", 68],
  ["circlearrowright", "\\circlearrowright", "Mũi tên tròn theo chiều kim đồng hồ", "Clockwise circular arrow", "arrow", 66],
  ["circlearrowleft", "\\circlearrowleft", "Mũi tên tròn ngược chiều kim đồng hồ", "Counterclockwise circular arrow", "arrow", 66],
  ["rightsquigarrow", "\\rightsquigarrow", "Mũi tên phải nguệch ngoạc", "Squiggly right arrow", "arrow", 70],
  ["twoheadrightarrow", "\\twoheadrightarrow", "Mũi tên phải hai đầu", "Two-headed right arrow", "arrow", 70],
  ["twoheadleftarrow", "\\twoheadleftarrow", "Mũi tên trái hai đầu", "Two-headed left arrow", "arrow", 70],
  ["Uparrow", "\\Uparrow", "Mũi tên kép lên", "Up double arrow", "arrow", 78],
  ["Downarrow", "\\Downarrow", "Mũi tên kép xuống", "Down double arrow", "arrow", 78],
  ["Updownarrow", "\\Updownarrow", "Mũi tên đôi hướng lên xuống", "Up-down double arrow", "arrow", 76],
  ["upuparrows", "\\upuparrows", "Mũi tên ghép đôi", "Paired up arrows", "arrow", 70],
  ["downdownarrows", "\\downdownarrows", "Cặp mũi tên xuống", "Paired down arrows", "arrow", 70],
  ["leftleftarrows", "\\leftleftarrows", "Cặp mũi tên trái", "Paired left arrows", "arrow", 72],
  ["rightrightarrows", "\\rightrightarrows", "Cặp mũi tên phải", "Paired right arrows", "arrow", 72],
  ["leftrightarrows", "\\leftrightarrows", "Mũi tên ghép trái phải", "Left-right paired arrows", "arrow", 74],
  ["Lleftarrow", "\\Lleftarrow", "Mũi tên ba bên trái", "Triple left arrow", "arrow", 66],
  ["Rrightarrow", "\\Rrightarrow", "Ba mũi tên phải", "Triple right arrow", "arrow", 66],
  ["leftarrowtail", "\\leftarrowtail", "Mũi tên trái có đuôi", "Left arrow with tail", "arrow", 68],
  ["rightarrowtail", "\\rightarrowtail", "Mũi tên phải có đuôi", "Right arrow with tail", "arrow", 68],
  ["looparrowleft", "\\looparrowleft", "Mũi tên vòng trái", "Left loop arrow", "arrow", 66],
  ["looparrowright", "\\looparrowright", "Mũi tên vòng phải", "Right loop arrow", "arrow", 66],
  ["curvearrowleft", "\\curvearrowleft", "Mũi tên cong trái", "Left curved arrow", "arrow", 66],
  ["curvearrowright", "\\curvearrowright", "Mũi tên cong phải", "Right curved arrow", "arrow", 66],
  ["leftrightsquigarrow", "\\leftrightsquigarrow", "Mũi tên ngoằn ngoèo trái phải", "Left-right squiggle arrow", "arrow", 68],
  ["dashleftarrow", "\\dashleftarrow", "Mũi tên trái nét đứt", "Dashed left arrow", "arrow", 64],
  ["dashrightarrow", "\\dashrightarrow", "Mũi tên phải nét đứt", "Dashed right arrow", "arrow", 64],
  ["Lsh", "\\Lsh", "Mũi tên dịch chuyển trái", "Left shift arrow", "arrow", 64],
  ["Rsh", "\\Rsh", "Mũi tên dịch chuyển phải", "Right shift arrow", "arrow", 64],
  ["multimap", "\\multimap", "Đa bản đồ", "Multimap", "arrow", 72],
  ["nleftarrow", "\\nleftarrow", "Mũi tên không trái", "Not left arrow", "arrow", 62],
  ["nrightarrow", "\\nrightarrow", "Mũi tên không phải", "Not right arrow", "arrow", 62],
  ["nleftrightarrow", "\\nleftrightarrow", "Không phải mũi tên trái phải", "Not left-right arrow", "arrow", 62],
  ["nLeftarrow", "\\nLeftarrow", "Mũi tên kép không trái", "Not left double arrow", "arrow", 60],
  ["nRightarrow", "\\nRightarrow", "Mũi tên kép không phải", "Not right double arrow", "arrow", 60],
  ["nLeftrightarrow", "\\nLeftrightarrow", "Mũi tên không tương đương", "Not equivalence arrow", "arrow", 60],
  ["upharpoonleft", "\\upharpoonleft", "Cây lao lên trái", "Up harpoon left", "arrow", 64],
  ["upharpoonright", "\\upharpoonright", "Lên lao phải", "Up harpoon right", "arrow", 64],
  ["downharpoonleft", "\\downharpoonleft", "Cây lao xuống bên trái", "Down harpoon left", "arrow", 64],
  ["downharpoonright", "\\downharpoonright", "Lao lao xuống bên phải", "Down harpoon right", "arrow", 64],
  ["mapsfrom", "↤", "Bản đồ từ", "Maps from", "arrow", 72],
  ["longmapsfrom", "⟻", "Bản đồ dài từ", "Long maps from", "arrow", 68],
  ["leadsto", "\\leadsto", "Dẫn đến", "Leads to", "arrow", 68],

  // 物理常用
  ["planck", "h", "Hằng số Planck", "Planck constant", "physics", 88],
  ["kb", "k_{\\mathrm{B}}", "Hằng số Boltzmann", "Boltzmann constant", "physics", 91],
  ["epsilon0", "\\varepsilon_{0}", "Độ thấm chân không", "Vacuum permittivity", "physics", 89],
  ["mu0", "\\mu_{0}", "Độ thấm chân không", "Vacuum permeability", "physics", 89],
  ["lightspeed", "c", "Tốc độ ánh sáng", "Speed of light", "physics", 86],
  ["electroncharge", "e", "Điện tích cơ bản", "Elementary charge", "physics", 84],
  ["laplacian", "\\nabla^{2}", "Laplacian", "Laplacian", "physics", 88],
  ["divergence", "\\nabla\\cdot", "Phân kỳ", "Divergence", "physics", 86],
  ["curl", "\\nabla\\times", "Uốn", "Curl", "physics", 86],
  ["dagger", "\\dagger", "Dao găm", "Dagger", "physics", 84],
  ["ddagger", "\\ddagger", "Dao găm đôi", "Double dagger", "physics", 72],
  ["tensorproduct", "\\otimes", "Sản phẩm Tenor", "Tensor product", "physics", 88],
  ["directsum", "\\oplus", "Tổng trực tiếp", "Direct sum", "physics", 82],
  ["hamiltonian-operator", "\\hat{H}", "Toán tử Hamilton", "Hamiltonian operator", "physics", 92],
  ["momentum-operator", "\\hat{\\mathbf{p}}", "Toán tử động lượng", "Momentum operator", "physics", 90],
  ["angular-momentum-operator", "\\hat{\\mathbf{L}}", "Toán tử xung lượng góc", "Angular momentum operator", "physics", 88],
  ["spin-operator", "\\hat{\\mathbf{S}}", "Toán tử quay", "Spin operator", "physics", 87],
  ["electric-field", "\\mathbf{E}", "Điện trường", "Electric field", "physics", 88],
  ["magnetic-field", "\\mathbf{B}", "Từ trường", "Magnetic field", "physics", 88],
  ["electric-displacement", "\\mathbf{D}", "Dịch chuyển điện", "Electric displacement", "physics", 80],
  ["magnetic-intensity", "\\mathbf{H}", "Cường độ từ trường", "Magnetic field intensity", "physics", 80],
  ["current-density", "\\mathbf{J}", "Mật độ dòng điện", "Current density", "physics", 82],
  ["kronecker-delta", "\\delta_{ij}", "đồng bằng Kronecker", "Kronecker delta", "physics", 84],
  ["levi-civita", "\\varepsilon_{ijk}", "Biểu tượng Levi-Civita", "Levi-Civita symbol", "physics", 82],
  ["four-gradient", "\\partial_{\\mu}", "Độ dốc bốn", "Four-gradient", "physics", 81],
  ["metric-tensor", "g_{\\mu\\nu}", "Tenxơ hệ mét", "Metric tensor", "physics", 81],
  ["dalembertian", "\\Box", "Toán tử D'Alembert", "D'Alembert operator", "physics", 80],
  ["imaginary-unit", "\\mathrm{i}", "Đơn vị tưởng tượng", "Imaginary unit", "physics", 76],
  ["euler-number", "\\mathrm{e}", "Số Euler", "Euler's number", "physics", 76],
  ["reduced-compton", "\\ell", "Kịch bản ell", "Script ell", "physics", 68],
  ["pauli-vector", "\\boldsymbol{\\sigma}", "Vector Pauli", "Pauli vector", "physics", 83],
];

const simpleCommands = simpleDefinitions.map(
  ([id, command, labelVi, labelEn, category, priority = 72, aliases = [], keywords = []]) =>
    makeCommand(
      id,
      command,
      command,
      command,
      labelVi,
      labelEn,
      category,
      priority,
      aliases,
      keywords,
    ),
);

export const additionalCommands: LatexCommand[] = [
  ...complexCommands,
  ...simpleCommands,
];
